# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 8
create_project -in_memory -part xc7a200tffg1156-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.cache/wt [current_project]
set_property parent.project_path /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/crc_gen.v
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/crc_chk.v
}
read_vhdl -library xil_defaultlib {
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/imports/hdl/TOP_LEVEL.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/hdl/params_package.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/cntrs_2_b_fifo_jw121.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/v_sec_60_4_in_64_out.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/sel_block.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/ff_la.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/acc_sync.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/v_sec_32_4_in_64_out.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/cnt32.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_3.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/sig_gen_prog.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/mux_4_to_1.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_1.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/buf8.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/start_sig_mux.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/Load_array_section_16.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/reg_64.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/veto_count.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/clk_mux_2_to_1_x_2.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/test_mux.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/reg_8.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/cnt64.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/load_ctl_1_phase_4ps_fs_sync.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/nim_plus_package_1.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/reg_32.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/ver_code.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_4.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/ps_hold_count.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/agrgate_8_by_8.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/DAC_Control.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/read_decode_p.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/reg_read_decode_p.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_2.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/cnt_64_simp.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/mux_2_1_16ch.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/agrgate16_1.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/cnt32_v2.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/load_array_64_v_ps.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/pol_sel.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/stsp_counter.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/mux64_2.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_ctrs.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/reg_16.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/scope_probe_4ch.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/nim_plus_blk_1_phase_4ps.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/hdl/burst_traffic_controller.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/hdl/reset_mgr.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/hdl/ethernet_interface.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/icmp_ping_checksum_calc.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/ip_checksum_calc.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/user_addrs_mux.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/data_manager/tx_seq_ctl.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/xmii_handler.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/data_manager/burst_controller_sm.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/create_packet.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/udp_data_splicer.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/ethernet_controller_wrapper.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/arp_reply.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/crc_splice.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/icmp_ping_shift_reg.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/or33.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/decipherer.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/dataout_mux.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/data_manager/data_manager.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/data_manager/ram_comm_dec.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/filter_data_out.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/data_manager/rx_ctl.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/fifo.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/address_container.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/ethImports/ethernet_controller/ethernet_controller.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/s_cnt32_v2.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/ag284.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/d_ff.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/clkd_burst_mux_8_to_1.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/bfifomux_w_ctlr.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/clkd_b_fifo_mux.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/cntrs_2_b_fifo.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/load_long_64_v_ps.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/long_pulse.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/mch_trig_out.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/trig_out_mux.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/acc_sync_shft_reg.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/mux_8_to_1.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/clk39_pattern.vhd
  /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/FW_Transfer_2018_01_24/dmux_ff.vhd
}
read_ip -quiet /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/xilinx_64b_counter/xilinx_64b_counter.xci
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/xilinx_64b_counter/xilinx_64b_counter_ooc.xdc]

read_ip -quiet /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_internalClocks/clk_wiz_internalClocks.xci
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_internalClocks/clk_wiz_internalClocks_board.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_internalClocks/clk_wiz_internalClocks.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_internalClocks/clk_wiz_internalClocks_ooc.xdc]

read_ip -quiet /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS.xci
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS_board.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS.xdc]
set_property used_in_implementation false [get_files -all /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/constrs_1/new/top_11.xdc
set_property used_in_implementation false [get_files /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/constrs_1/new/top_11.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a200tffg1156-2 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
