# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tffg1156-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.cache/wt} [current_project]
set_property parent.project_path {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.runs/xilinx_64b_counter_synth_1/xilinx_64b_counter.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.runs/xilinx_64b_counter_synth_1/xilinx_64b_counter.dcp}}]
add_files -quiet {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.runs/clk_wiz_1_synth_1/clk_wiz_1.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.runs/clk_wiz_1_synth_1/clk_wiz_1.dcp}}]
add_files -quiet {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.runs/clk_wiz_internalClocks_synth_1/clk_wiz_internalClocks.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.runs/clk_wiz_internalClocks_synth_1/clk_wiz_internalClocks.dcp}}]
add_files -quiet {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.runs/NIM_CLKS_synth_1/NIM_CLKS.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.runs/NIM_CLKS_synth_1/NIM_CLKS.dcp}}]
read_verilog -library xil_defaultlib {
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/crc_gen.v}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/crc_chk.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.srcs/sources_1/imports/hdl/TOP_LEVEL.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/hdl/params_package.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/cntrs_2_b_fifo_jw121.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/v_sec_60_4_in_64_out.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/sel_block.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/ff_la.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/acc_sync.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/v_sec_32_4_in_64_out.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/cnt32.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_3.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/sig_gen_prog.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/mux_4_to_1.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_1.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/buf8.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/start_sig_mux.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/Load_array_section_16.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/reg_64.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/veto_count.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/clk_mux_2_to_1_x_2.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/test_mux.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/reg_8.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/cnt64.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/load_ctl_1_phase_4ps_fs_sync.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/nim_plus_package_1.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/reg_32.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/ver_code.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_4.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/ps_hold_count.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/agrgate_8_by_8.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/DAC_Control.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/read_decode_p.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/reg_read_decode_p.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_2.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/cnt_64_simp.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/mux_2_1_16ch.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/agrgate16_1.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/cnt32_v2.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/load_array_64_v_ps.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/pol_sel.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/stsp_counter.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/mux64_2.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/decode_addr_NIM_Plus_ctrs.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/reg_16.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/scope_probe_4ch.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/nim_plus_blk_1_phase_4ps.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/hdl/burst_traffic_controller.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/hdl/reset_mgr.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/hdl/ethernet_interface.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/icmp_ping_checksum_calc.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/ip_checksum_calc.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/user_addrs_mux.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/data_manager/tx_seq_ctl.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/xmii_handler.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/data_manager/burst_controller_sm.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/create_packet.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/udp_data_splicer.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/ethernet_controller_wrapper.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/arp_reply.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/crc_splice.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/icmp_ping_shift_reg.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/or33.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/decipherer.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/dataout_mux.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/data_manager/data_manager.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/data_manager/ram_comm_dec.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/filter_data_out.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/data_manager/rx_ctl.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/fifo.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/address_container.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/ethImports/ethernet_controller/ethernet_controller.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/s_cnt32_v2.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/ag284.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/d_ff.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/clkd_burst_mux_8_to_1.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/bfifomux_w_ctlr.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/clkd_b_fifo_mux.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/cntrs_2_b_fifo.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/load_long_64_v_ps.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/long_pulse.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/mch_trig_out.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/trig_out_mux.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/acc_sync_shft_reg.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/mux_8_to_1.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/clk39_pattern.vhd}
  {C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/FW_Transfer_2018_01_24/dmux_ff.vhd}
}
read_xdc {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.srcs/constrs_1/new/top_11.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/bhawks/Documents/Vivado Projects/nim_plus2/top/top.srcs/constrs_1/new/top_11.xdc}}]

synth_design -top top -part xc7a200tffg1156-2 -flatten_hierarchy none
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
