# Autogenerated project build script
# Tue Jul 17 12:54:29 2018

set outputDir /home/rrivera/ots/srcs/otsdaq-firmware/tmpwork/top
file mkdir $outputDir
create_project top $outputDir -part xc7a200tffg1156-2 -force
if {[string equal [get_filesets -quiet constrs_1] ""]} {create_fileset -constrset constrs_1}
if {[string equal [get_filesets -quiet sources_1] ""]} {create_fileset -srcset sources_1}
if {[string equal [get_filesets -quiet ise_1] ""]} {create_fileset -srcset ise_1}
source ../cactus/boards/captan_plus/firmware/cfg/settings_v7.vivado.tcl
set_property USED_IN implementation [import_files -norecurse -fileset constrs_1 ../cactus/boards/captan_plus/firmware/ucf/ethernet_pins25.tcl]
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_gen.v
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_chk.v
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ethernet_controller.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/xmii_handler.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/decipherer.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/filter_data_out.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/address_container.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/icmp_ping_shift_reg.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/create_packet.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/dataout_mux.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/arp_reply.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/udp_data_splicer.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_splice.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/icmp_ping_checksum_calc.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/or33.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/user_addrs_mux.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ethernet_controller_wrapper.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/fifo.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ip_checksum_calc.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/burst_controller_sm.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/rx_ctl.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/ram_comm_dec.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/tx_seq_ctl.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/data_manager.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/reset_mgr.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_interface.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/params_package.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/burst_traffic_controller.vhd
set_property USED_IN implementation [import_files -norecurse -fileset constrs_1 ../cactus/projects/ethernet_data_gen/firmware/ucf/clock_constraints.tcl]
import_files -norecurse -fileset sources_1 ../cactus/projects/ethernet_data_gen/firmware/hdl/TOP_LEVEL.vhd
set_property top top [current_fileset]
set_property "steps.synth_design.args.flatten_hierarchy" "none" [get_runs synth_1]
