# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS.xci
# IP: The module: 'NIM_CLKS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'NIM_CLKS'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS.xdc
# XDC: The top module name and the constraint reference have the same name: 'NIM_CLKS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NIM_CLKS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS.xci
# IP: The module: 'NIM_CLKS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'NIM_CLKS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS.xdc
# XDC: The top module name and the constraint reference have the same name: 'NIM_CLKS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/NIM_CLKS/NIM_CLKS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NIM_CLKS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
