set_property SRC_FILE_INFO {cfile:/home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/constrs_1/new/top.xdc rfile:../../../top.srcs/constrs_1/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list MASTER_CLK]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {reg_cnt[0]} {reg_cnt[1]} {reg_cnt[2]} {reg_cnt[3]} {reg_cnt[4]} {reg_cnt[5]} {reg_cnt[6]} {reg_cnt[7]} {reg_cnt[8]} {reg_cnt[9]} {reg_cnt[10]} {reg_cnt[11]} {reg_cnt[12]} {reg_cnt[13]} {reg_cnt[14]} {reg_cnt[15]} {reg_cnt[16]} {reg_cnt[17]} {reg_cnt[18]} {reg_cnt[19]} {reg_cnt[20]} {reg_cnt[21]} {reg_cnt[22]} {reg_cnt[23]} {reg_cnt[24]} {reg_cnt[25]} {reg_cnt[26]} {reg_cnt[27]} {reg_cnt[28]} {reg_cnt[29]} {reg_cnt[30]} {reg_cnt[31]} {reg_cnt[32]} {reg_cnt[33]} {reg_cnt[34]} {reg_cnt[35]} {reg_cnt[36]} {reg_cnt[37]} {reg_cnt[38]} {reg_cnt[39]} {reg_cnt[40]} {reg_cnt[41]} {reg_cnt[42]} {reg_cnt[43]} {reg_cnt[44]} {reg_cnt[45]} {reg_cnt[46]} {reg_cnt[47]} {reg_cnt[48]} {reg_cnt[49]} {reg_cnt[50]} {reg_cnt[51]} {reg_cnt[52]} {reg_cnt[53]} {reg_cnt[54]} {reg_cnt[55]} {reg_cnt[56]} {reg_cnt[57]} {reg_cnt[58]} {reg_cnt[59]} {reg_cnt[60]} {reg_cnt[61]} {reg_cnt[62]} {reg_cnt[63]}]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {delay_cnt[0]} {delay_cnt[1]} {delay_cnt[2]} {delay_cnt[3]} {delay_cnt[4]} {delay_cnt[5]} {delay_cnt[6]} {delay_cnt[7]} {delay_cnt[8]} {delay_cnt[9]} {delay_cnt[10]} {delay_cnt[11]} {delay_cnt[12]} {delay_cnt[13]} {delay_cnt[14]} {delay_cnt[15]} {delay_cnt[16]} {delay_cnt[17]} {delay_cnt[18]} {delay_cnt[19]} {delay_cnt[20]} {delay_cnt[21]} {delay_cnt[22]} {delay_cnt[23]} {delay_cnt[24]} {delay_cnt[25]} {delay_cnt[26]} {delay_cnt[27]} {delay_cnt[28]} {delay_cnt[29]} {delay_cnt[30]} {delay_cnt[31]} {delay_cnt[32]} {delay_cnt[33]} {delay_cnt[34]} {delay_cnt[35]} {delay_cnt[36]} {delay_cnt[37]} {delay_cnt[38]} {delay_cnt[39]} {delay_cnt[40]} {delay_cnt[41]} {delay_cnt[42]} {delay_cnt[43]} {delay_cnt[44]} {delay_cnt[45]} {delay_cnt[46]} {delay_cnt[47]} {delay_cnt[48]} {delay_cnt[49]} {delay_cnt[50]} {delay_cnt[51]} {delay_cnt[52]} {delay_cnt[53]} {delay_cnt[54]} {delay_cnt[55]} {delay_cnt[56]} {delay_cnt[57]} {delay_cnt[58]} {delay_cnt[59]} {delay_cnt[60]} {delay_cnt[61]} {delay_cnt[62]} {delay_cnt[63]}]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {cnt[0]} {cnt[1]} {cnt[2]}]]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {reg_rate[0]} {reg_rate[1]} {reg_rate[2]} {reg_rate[3]} {reg_rate[4]} {reg_rate[5]} {reg_rate[6]} {reg_rate[7]} {reg_rate[8]} {reg_rate[9]} {reg_rate[10]} {reg_rate[11]} {reg_rate[12]} {reg_rate[13]} {reg_rate[14]} {reg_rate[15]} {reg_rate[16]} {reg_rate[17]} {reg_rate[18]} {reg_rate[19]} {reg_rate[20]} {reg_rate[21]} {reg_rate[22]} {reg_rate[23]} {reg_rate[24]} {reg_rate[25]} {reg_rate[26]} {reg_rate[27]} {reg_rate[28]} {reg_rate[29]} {reg_rate[30]} {reg_rate[31]} {reg_rate[32]} {reg_rate[33]} {reg_rate[34]} {reg_rate[35]} {reg_rate[36]} {reg_rate[37]} {reg_rate[38]} {reg_rate[39]} {reg_rate[40]} {reg_rate[41]} {reg_rate[42]} {reg_rate[43]} {reg_rate[44]} {reg_rate[45]} {reg_rate[46]} {reg_rate[47]} {reg_rate[48]} {reg_rate[49]} {reg_rate[50]} {reg_rate[51]} {reg_rate[52]} {reg_rate[53]} {reg_rate[54]} {reg_rate[55]} {reg_rate[56]} {reg_rate[57]} {reg_rate[58]} {reg_rate[59]} {reg_rate[60]} {reg_rate[61]} {reg_rate[62]} {reg_rate[63]}]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list b_data_we]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list rx_wren]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets MASTER_CLK]
