# Autogenerated project build script
# Tue Apr 11 08:34:20 2017

project new top
project set family virtex4
project set device xc4vlx25
project set package ff668
project set speed -10
source ../cactus/boards/captan/firmware/cfg/settings_v7.ise.tcl
xfile add ../cactus/boards/captan/firmware/ucf/pins_v2.ucf -copy
exec mkdir -p ipcore_dir
exec cp ../cactus/boards/captan/firmware/cfg/coregen.cgp ipcore_dir
exec cp ../cactus/components/ots_ethernet/firmware/cgn/ADDR_FIFO.xco ipcore_dir
cd ipcore_dir
exec coregen -r -b ADDR_FIFO.xco -p coregen.cgp >& coregen.out
cd ..
xfile add ipcore_dir/ADDR_FIFO.xco -copy
exec mkdir -p ipcore_dir
exec cp ../cactus/boards/captan/firmware/cfg/coregen.cgp ipcore_dir
exec cp ../cactus/components/ots_ethernet/firmware/cgn/INFO_FIFO_0.xco ipcore_dir
cd ipcore_dir
exec coregen -r -b INFO_FIFO_0.xco -p coregen.cgp >& coregen.out
cd ..
xfile add ipcore_dir/INFO_FIFO_0.xco -copy
exec mkdir -p ipcore_dir
exec cp ../cactus/boards/captan/firmware/cfg/coregen.cgp ipcore_dir
exec cp ../cactus/components/ots_ethernet/firmware/cgn/DATA_FIFO_0.xco ipcore_dir
cd ipcore_dir
exec coregen -r -b DATA_FIFO_0.xco -p coregen.cgp >& coregen.out
cd ..
xfile add ipcore_dir/DATA_FIFO_0.xco -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_gen.v -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_chk.v -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ethernet_controller.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/xmii_handler.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/decipherer.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/filter_data_out.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/address_container.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/icmp_ping_shift_reg.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/create_packet.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/dataout_mux.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/arp_reply.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/udp_data_splicer.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_splice.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/icmp_ping_checksum_calc.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/or33.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/user_addrs_mux.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ethernet_controller_wrapper.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ip_checksum_calc.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/burst_controller_sm.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/rx_ctl.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/ram_comm_dec.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/tx_seq_ctl.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/data_manager.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/reset_mgr.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_interface.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/params_package.vhd -copy
xfile add ../cactus/components/ots_ethernet/firmware/hdl/burst_traffic_controller.vhd -copy
xfile add ../cactus/projects/ethernet_null_algo/firmware/ucf/clock_constraints.ucf -copy
xfile add ../cactus/projects/ethernet_null_algo/firmware/hdl/TOP_LEVEL.vhd -copy
project set top rtl top
project close
