# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/streamipbuf/streamipbuf.xci
# IP: The module: 'streamipbuf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/streamipbuf/streamipbuf/streamipbuf_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'streamipbuf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/streamipbuf/streamipbuf/streamipbuf.xdc
# XDC: The top module name and the constraint reference have the same name: 'streamipbuf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/streamipbuf/streamipbuf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'streamipbuf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/streamipbuf/streamipbuf.xci
# IP: The module: 'streamipbuf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/streamipbuf/streamipbuf/streamipbuf_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'streamipbuf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/streamipbuf/streamipbuf/streamipbuf.xdc
# XDC: The top module name and the constraint reference have the same name: 'streamipbuf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/streamipbuf/streamipbuf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'streamipbuf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
