#ChipScope Core Inserter Project File Version 3.0
#Tue Jul 19 15:02:45 CDT 2016
Project.device.designInputFile=D\:\\Projects\\Testbeam I\\CMS_TB_MASTER_\\CMS_TB_MASTER_\\GEL_CAPTAN\\TOP_LEVEL_cs.ngc
Project.device.designOutputFile=D\:\\Projects\\Testbeam I\\CMS_TB_MASTER_\\CMS_TB_MASTER_\\GEL_CAPTAN\\TOP_LEVEL_cs.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\Projects\\Testbeam I\\CMS_TB_MASTER_\\CMS_TB_MASTER_\\GEL_CAPTAN\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=*mclk_have*
Project.filter<11>=*EXT*
Project.filter<12>=*psi_dig*
Project.filter<13>=*PSI_DIG_BLK_*
Project.filter<14>=*PSI_DIG_BLK_0*
Project.filter<15>=*PSI_DIG_BLK0*
Project.filter<16>=*PSI_DIG_BLK*
Project.filter<17>=*dataout*
Project.filter<18>=*dataout_we*
Project.filter<1>=*bypass*
Project.filter<2>=*token*
Project.filter<3>=*rd_to*
Project.filter<4>=*
Project.filter<5>=*rd_t*
Project.filter<6>=*dig_ctrl*
Project.filter<7>=*token_out*
Project.filter<8>=*token_in*
Project.filter<9>=*sm*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=MASTER_CLK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=psi_dig_read<0>
Project.unit<0>.dataChannel<10>=psi_dig_ctrl<1>
Project.unit<0>.dataChannel<11>=psi_dig_ctrl<4>
Project.unit<0>.dataChannel<12>=psi_dig_ctrl<5>
Project.unit<0>.dataChannel<13>=psi_dig_ctrl<6>
Project.unit<0>.dataChannel<14>=psi_dig_ctrl<7>
Project.unit<0>.dataChannel<15>=EXT_TRIGG
Project.unit<0>.dataChannel<16>=PSI_Dig_Blk_0/XLXI_6064 mclk_have_data
Project.unit<0>.dataChannel<17>=PSI_Dig_Blk_1/XLXI_6064 mclk_have_data
Project.unit<0>.dataChannel<18>=PSI_Dig_Blk_0/XLXI_6064 sm_ready
Project.unit<0>.dataChannel<19>=PSI_Dig_Blk_1/XLXI_6064 sm_ready
Project.unit<0>.dataChannel<1>=psi_dig_read<1>
Project.unit<0>.dataChannel<20>=psi_token_in<0>
Project.unit<0>.dataChannel<21>=psi_token_in<1>
Project.unit<0>.dataChannel<22>=psi_token_out<0>
Project.unit<0>.dataChannel<23>=psi_token_out<1>
Project.unit<0>.dataChannel<2>=PSI_Dig_Blk_0/CHIP_TMGR/have_data
Project.unit<0>.dataChannel<3>=PSI_Dig_Blk_1/CHIP_TMGR/have_data
Project.unit<0>.dataChannel<4>=PSI_Dig_Blk_0/CHIP_TMGR/we_out
Project.unit<0>.dataChannel<5>=PSI_Dig_Blk_1/CHIP_TMGR/we_out
Project.unit<0>.dataChannel<6>=PSI_Dig_Blk_0/psi_dec_data_we
Project.unit<0>.dataChannel<7>=PSI_Dig_Blk_1/psi_dec_data_we
Project.unit<0>.dataChannel<8>=bypass_token_stack
Project.unit<0>.dataChannel<9>=psi_dig_ctrl<0>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=24
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=XLXI_5836 busy
Project.unit<0>.triggerChannel<0><10>=XLXI_5836 psi_clk_delay<3>
Project.unit<0>.triggerChannel<0><11>=XLXI_5836 psi_clk_delay<4>
Project.unit<0>.triggerChannel<0><12>=XLXI_5836 psi_clk_delay<5>
Project.unit<0>.triggerChannel<0><13>=XLXI_5836 psi_clk_delay<6>
Project.unit<0>.triggerChannel<0><14>=XLXI_5836 psi_clk_delay<7>
Project.unit<0>.triggerChannel<0><15>=XLXI_5836 psi_clk_delay_cnt<0>
Project.unit<0>.triggerChannel<0><16>=XLXI_5836 psi_clk_delay_cnt<1>
Project.unit<0>.triggerChannel<0><17>=XLXI_5836 psi_clk_delay_cnt<2>
Project.unit<0>.triggerChannel<0><18>=XLXI_5836 psi_clk_delay_cnt<3>
Project.unit<0>.triggerChannel<0><19>=XLXI_5836 psi_clk_delay_cnt<4>
Project.unit<0>.triggerChannel<0><1>=XLXI_5836 coinc
Project.unit<0>.triggerChannel<0><20>=XLXI_5836 psi_clk_delay_cnt<5>
Project.unit<0>.triggerChannel<0><21>=XLXI_5836 psi_clk_delay_cnt<6>
Project.unit<0>.triggerChannel<0><22>=XLXI_5836 psi_clk_delay_cnt<7>
Project.unit<0>.triggerChannel<0><23>=XLXI_5836 scin<0>
Project.unit<0>.triggerChannel<0><24>=XLXI_5836 scin<1>
Project.unit<0>.triggerChannel<0><25>=XLXI_5836 scin<2>
Project.unit<0>.triggerChannel<0><26>=XLXI_5836 scin_cnt_sig<0>
Project.unit<0>.triggerChannel<0><27>=XLXI_5836 scin_cnt_sig<1>
Project.unit<0>.triggerChannel<0><28>=XLXI_5836 scin_cnt_sig<2>
Project.unit<0>.triggerChannel<0><29>=XLXI_5836 scin_cnt_sig<3>
Project.unit<0>.triggerChannel<0><2>=XLXI_5836 delay_coinc
Project.unit<0>.triggerChannel<0><30>=XLXI_5836 scin_cnt_sig<4>
Project.unit<0>.triggerChannel<0><31>=XLXI_5836 scin_cnt_sig<5>
Project.unit<0>.triggerChannel<0><32>=XLXI_5836 scin_cnt_sig<6>
Project.unit<0>.triggerChannel<0><33>=XLXI_5836 scin_cnt_sig<7>
Project.unit<0>.triggerChannel<0><34>=XLXI_5836 scin_cnt_sig<8>
Project.unit<0>.triggerChannel<0><35>=XLXI_5836 scin_sig<0>
Project.unit<0>.triggerChannel<0><36>=XLXI_5836 scin_sig<1>
Project.unit<0>.triggerChannel<0><37>=XLXI_5836 scin_sig<2>
Project.unit<0>.triggerChannel<0><38>=XLXI_5836 tmp_coinc
Project.unit<0>.triggerChannel<0><39>=XLXI_5836 trig_fifo_empty
Project.unit<0>.triggerChannel<0><3>=XLXI_5836 coinc_count<0>
Project.unit<0>.triggerChannel<0><40>=XLXI_5836 trig_fifo_re
Project.unit<0>.triggerChannel<0><41>=XLXI_5836 trig_fifo_we_sig
Project.unit<0>.triggerChannel<0><42>=XLXI_5836 trig_out
Project.unit<0>.triggerChannel<0><43>=XLXI_5836 veto_duration_sig<0>
Project.unit<0>.triggerChannel<0><44>=XLXI_5836 veto_duration_sig<1>
Project.unit<0>.triggerChannel<0><45>=XLXI_5836 veto_duration_sig<2>
Project.unit<0>.triggerChannel<0><46>=XLXI_5836 veto_duration_sig<3>
Project.unit<0>.triggerChannel<0><47>=XLXI_5836 veto_duration_sig<4>
Project.unit<0>.triggerChannel<0><48>=XLXI_5836 veto_duration_sig<5>
Project.unit<0>.triggerChannel<0><49>=XLXI_5836 veto_duration_sig<6>
Project.unit<0>.triggerChannel<0><4>=XLXI_5836 coinc_count<1>
Project.unit<0>.triggerChannel<0><50>=XLXI_5836 veto_duration_sig<7>
Project.unit<0>.triggerChannel<0><51>=XLXI_5836 veto_duration_sig<8>
Project.unit<0>.triggerChannel<0><52>=XLXI_5836 veto_duration_sig<9>
Project.unit<0>.triggerChannel<0><53>=XLXI_5836 veto_duration_sig<10>
Project.unit<0>.triggerChannel<0><54>=
Project.unit<0>.triggerChannel<0><55>=
Project.unit<0>.triggerChannel<0><56>=
Project.unit<0>.triggerChannel<0><57>=
Project.unit<0>.triggerChannel<0><58>=
Project.unit<0>.triggerChannel<0><59>=
Project.unit<0>.triggerChannel<0><5>=XLXI_5836 coinc_count<2>
Project.unit<0>.triggerChannel<0><60>=
Project.unit<0>.triggerChannel<0><61>=
Project.unit<0>.triggerChannel<0><62>=
Project.unit<0>.triggerChannel<0><63>=
Project.unit<0>.triggerChannel<0><64>=
Project.unit<0>.triggerChannel<0><65>=
Project.unit<0>.triggerChannel<0><66>=
Project.unit<0>.triggerChannel<0><67>=
Project.unit<0>.triggerChannel<0><68>=
Project.unit<0>.triggerChannel<0><69>=
Project.unit<0>.triggerChannel<0><6>=XLXI_5836 coinc_count<3>
Project.unit<0>.triggerChannel<0><70>=
Project.unit<0>.triggerChannel<0><71>=
Project.unit<0>.triggerChannel<0><72>=
Project.unit<0>.triggerChannel<0><73>=
Project.unit<0>.triggerChannel<0><74>=
Project.unit<0>.triggerChannel<0><75>=
Project.unit<0>.triggerChannel<0><76>=
Project.unit<0>.triggerChannel<0><77>=
Project.unit<0>.triggerChannel<0><78>=
Project.unit<0>.triggerChannel<0><79>=
Project.unit<0>.triggerChannel<0><7>=XLXI_5836 psi_clk_delay<0>
Project.unit<0>.triggerChannel<0><80>=
Project.unit<0>.triggerChannel<0><81>=
Project.unit<0>.triggerChannel<0><82>=
Project.unit<0>.triggerChannel<0><83>=
Project.unit<0>.triggerChannel<0><84>=
Project.unit<0>.triggerChannel<0><85>=
Project.unit<0>.triggerChannel<0><86>=
Project.unit<0>.triggerChannel<0><87>=
Project.unit<0>.triggerChannel<0><88>=
Project.unit<0>.triggerChannel<0><89>=
Project.unit<0>.triggerChannel<0><8>=XLXI_5836 psi_clk_delay<1>
Project.unit<0>.triggerChannel<0><90>=
Project.unit<0>.triggerChannel<0><91>=
Project.unit<0>.triggerChannel<0><92>=
Project.unit<0>.triggerChannel<0><93>=
Project.unit<0>.triggerChannel<0><94>=
Project.unit<0>.triggerChannel<0><95>=
Project.unit<0>.triggerChannel<0><96>=
Project.unit<0>.triggerChannel<0><97>=
Project.unit<0>.triggerChannel<0><98>=
Project.unit<0>.triggerChannel<0><99>=
Project.unit<0>.triggerChannel<0><9>=XLXI_5836 psi_clk_delay<2>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=5
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=54
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
