# Autogenerated project build script
# Tue Mar  8 12:14:49 2016

set outputDir /home/rrivera/ots/srcs/otsdaq-firmware/work/top
file mkdir $outputDir
create_project top $outputDir -part xc7k325tffg900-2 -force
if {[string equal [get_filesets -quiet constrs_1] ""]} {create_fileset -constrset constrs_1}
if {[string equal [get_filesets -quiet sources_1] ""]} {create_fileset -srcset sources_1}
if {[string equal [get_filesets -quiet ise_1] ""]} {create_fileset -srcset ise_1}
source ../cactus/boards/kc705/firmware/cfg/settings_v7.vivado.tcl
set_property USED_IN implementation [import_files -norecurse -fileset constrs_1 ../cactus/projects/strip_mvp/firmware/ucf/clock_constraints.tcl]
set_property USED_IN implementation [import_files -norecurse -fileset constrs_1 ../cactus/projects/strip_mvp/firmware/ucf/pins_kc705.tcl]
set_property USED_IN implementation [import_files -norecurse -fileset constrs_1 ../cactus/boards/kc705/firmware/ucf/pins.tcl]
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/cgn/packetfifo.xci
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/cgn/streamipbuf.xci
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/cgn/strips_mclk_mmcm.xci
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/cgn/chip_fifo.xci
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/cgn/trigbuf.xci
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/iobus.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/fastbcocounter.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/stripsc.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/stripfifo.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/stripdacspi.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/strip_interface.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/stripana.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/stripclk.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/trigproc.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/stripdac.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/stripstream.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/striptbm.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/trigprim.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/chipserdes.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/strips_fssr2/firmware/hdl/stripreset.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_gen.v
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_chk.v
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ethernet_controller.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/xmii_handler.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/decipherer.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/filter_data_out.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/address_container.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/icmp_ping_shift_reg.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/create_packet.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/dataout_mux.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/arp_reply.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/udp_data_splicer.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_splice.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/icmp_ping_checksum_calc.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/or33.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/user_addrs_mux.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ethernet_controller_wrapper.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/fifo.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ip_checksum_calc.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/burst_controller_sm.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/rx_ctl.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/ram_comm_dec.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/tx_seq_ctl.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/data_manager/data_manager.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/reset_mgr.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/ethernet_interface.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/params_package.vhd
import_files -norecurse -fileset sources_1 ../cactus/components/ots_ethernet/firmware/hdl/burst_traffic_controller.vhd
import_files -norecurse -fileset sources_1 ../cactus/projects/strip_mvp/firmware/hdl/TOP_LEVEL.vhd
set_property top top [current_fileset]
set_property "steps.synth_design.args.flatten_hierarchy" "none" [get_runs synth_1]
upgrade_ip [get_ips packetfifo]
upgrade_ip [get_ips streamipbuf]
upgrade_ip [get_ips strips_mclk_mmcm]
upgrade_ip [get_ips chip_fifo]
upgrade_ip [get_ips trigbuf]
create_ip_run [get_files $outputDir/top.srcs/sources_1/ip/packetfifo/packetfifo.xci]
create_ip_run [get_files $outputDir/top.srcs/sources_1/ip/streamipbuf/streamipbuf.xci]
create_ip_run [get_files $outputDir/top.srcs/sources_1/ip/strips_mclk_mmcm/strips_mclk_mmcm.xci]
create_ip_run [get_files $outputDir/top.srcs/sources_1/ip/chip_fifo/chip_fifo.xci]
create_ip_run [get_files $outputDir/top.srcs/sources_1/ip/trigbuf/trigbuf.xci]
launch_run packetfifo_synth_1
launch_run streamipbuf_synth_1
launch_run strips_mclk_mmcm_synth_1
launch_run chip_fifo_synth_1
launch_run trigbuf_synth_1
