# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aprosser/ftbf_april2018/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/xilinx_64b_counter/xilinx_64b_counter.xci
# IP: The module: 'xilinx_64b_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aprosser/ftbf_april2018/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/xilinx_64b_counter/xilinx_64b_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_64b_counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/aprosser/ftbf_april2018/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/xilinx_64b_counter/xilinx_64b_counter.xci
# IP: The module: 'xilinx_64b_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aprosser/ftbf_april2018/otsdaq-firmware/cactus/projects/nim_plus_x/top/top.srcs/sources_1/ip/xilinx_64b_counter/xilinx_64b_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_64b_counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
