#ChipScope Core Inserter Project File Version 3.0
#Wed May 09 11:24:30 CDT 2018
Project.device.designInputFile=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_master_dig/GEL_CAPTAN/TOP_LEVEL_cs.ngc
Project.device.designOutputFile=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_master_dig/GEL_CAPTAN/TOP_LEVEL_cs.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_master_dig/GEL_CAPTAN/_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*trig*
Project.filter<10>=*error*
Project.filter<11>=*ttle*
Project.filter<12>=*throttle*
Project.filter<13>=throttle*
Project.filter<14>=*ovf*
Project.filter<15>=*error_reset_req*
Project.filter<16>=*have_data*
Project.filter<17>=*we_out*
Project.filter<18>=*psi_dec*
Project.filter<1>=*trigger*
Project.filter<2>=*MASTER*
Project.filter<3>=
Project.filter<4>=*scin*
Project.filter<5>=*sel*
Project.filter<6>=*sender*
Project.filter<7>=*psi*
Project.filter<8>=*count*
Project.filter<9>=*cnt*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=MASTER_CLK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=psi_dig_read<0>
Project.unit<0>.dataChannel<10>=PSI_Dig_Blk_1/psi_dec_data_we
Project.unit<0>.dataChannel<11>=PSI_Dig_Blk_2/psi_dec_data_we
Project.unit<0>.dataChannel<12>=bypass_token_stack
Project.unit<0>.dataChannel<13>=psi_dig_ctrl<0>
Project.unit<0>.dataChannel<14>=psi_dig_ctrl<1>
Project.unit<0>.dataChannel<15>=psi_dig_ctrl<4>
Project.unit<0>.dataChannel<16>=psi_dig_ctrl<5>
Project.unit<0>.dataChannel<17>=psi_dig_ctrl<6>
Project.unit<0>.dataChannel<18>=psi_dig_ctrl<7>
Project.unit<0>.dataChannel<19>=PSI_Dig_Blk_0/XLXI_6064 mclk_have_data
Project.unit<0>.dataChannel<1>=psi_dig_read<1>
Project.unit<0>.dataChannel<20>=PSI_Dig_Blk_1/XLXI_6064 mclk_have_data
Project.unit<0>.dataChannel<21>=PSI_Dig_Blk_2/XLXI_6064 mclk_have_data
Project.unit<0>.dataChannel<22>=PSI_Dig_Blk_0/XLXI_6064 sm_ready
Project.unit<0>.dataChannel<23>=PSI_Dig_Blk_1/XLXI_6064 sm_ready
Project.unit<0>.dataChannel<24>=PSI_Dig_Blk_2/XLXI_6064 sm_ready
Project.unit<0>.dataChannel<25>=psi_token_in<0>
Project.unit<0>.dataChannel<26>=psi_token_in<1>
Project.unit<0>.dataChannel<27>=psi_token_in<2>
Project.unit<0>.dataChannel<28>=psi_token_out<0>
Project.unit<0>.dataChannel<29>=psi_token_out<1>
Project.unit<0>.dataChannel<2>=psi_dig_read<2>
Project.unit<0>.dataChannel<30>=psi_token_out<2>
Project.unit<0>.dataChannel<31>=EXT_TRIGG
Project.unit<0>.dataChannel<32>=EXT_CLK
Project.unit<0>.dataChannel<33>=psi_extdom_trig
Project.unit<0>.dataChannel<34>=psi_dig_data_delay_inc
Project.unit<0>.dataChannel<35>=psi_dig_data_delay_rst
Project.unit<0>.dataChannel<36>=psi_data_out<0>
Project.unit<0>.dataChannel<37>=psi_data_out<1>
Project.unit<0>.dataChannel<38>=psi_data_out<2>
Project.unit<0>.dataChannel<39>=psi_token_reset_n<0>
Project.unit<0>.dataChannel<3>=PSI_Dig_Blk_0/CHIP_TMGR/have_data
Project.unit<0>.dataChannel<40>=psi_token_reset_n<1>
Project.unit<0>.dataChannel<41>=psi_token_reset_n<2>
Project.unit<0>.dataChannel<42>=error_reset_req<0>
Project.unit<0>.dataChannel<43>=error_reset_req<1>
Project.unit<0>.dataChannel<44>=error_reset_req<2>
Project.unit<0>.dataChannel<45>=TokenStack_vector_0 ovf_flow
Project.unit<0>.dataChannel<46>=TokenStack_vector_1 ovf_flow
Project.unit<0>.dataChannel<47>=TokenStack_vector_2 ovf_flow
Project.unit<0>.dataChannel<48>=PSI_Dig_Blk_0/XLXI_6064 error
Project.unit<0>.dataChannel<49>=PSI_Dig_Blk_1/XLXI_6064 error
Project.unit<0>.dataChannel<4>=PSI_Dig_Blk_1/CHIP_TMGR/have_data
Project.unit<0>.dataChannel<50>=PSI_Dig_Blk_2/XLXI_6064 error
Project.unit<0>.dataChannel<51>=TokenStack_vector_0 count<0>
Project.unit<0>.dataChannel<52>=TokenStack_vector_0 count<1>
Project.unit<0>.dataChannel<53>=TokenStack_vector_0 count<2>
Project.unit<0>.dataChannel<54>=TokenStack_vector_0 count<3>
Project.unit<0>.dataChannel<55>=TokenStack_vector_1 count<0>
Project.unit<0>.dataChannel<56>=TokenStack_vector_1 count<1>
Project.unit<0>.dataChannel<57>=TokenStack_vector_1 count<2>
Project.unit<0>.dataChannel<58>=TokenStack_vector_1 count<3>
Project.unit<0>.dataChannel<59>=TokenStack_vector_2 count<0>
Project.unit<0>.dataChannel<5>=PSI_Dig_Blk_2/CHIP_TMGR/have_data
Project.unit<0>.dataChannel<60>=TokenStack_vector_2 count<1>
Project.unit<0>.dataChannel<61>=TokenStack_vector_2 count<2>
Project.unit<0>.dataChannel<62>=TokenStack_vector_2 count<3>
Project.unit<0>.dataChannel<63>=PSI_CLK0
Project.unit<0>.dataChannel<64>=psi_cmd_sender_dout<0>
Project.unit<0>.dataChannel<65>=psi_cmd_sender_dout<1>
Project.unit<0>.dataChannel<66>=psi_cmd_sender_dout<2>
Project.unit<0>.dataChannel<67>=psi_out_clk_sel<0>
Project.unit<0>.dataChannel<68>=psi_out_clk_sel<1>
Project.unit<0>.dataChannel<69>=psi_out_clk_sel<2>
Project.unit<0>.dataChannel<6>=PSI_Dig_Blk_0/CHIP_TMGR/we_out
Project.unit<0>.dataChannel<70>=psi_out_clk_sel<3>
Project.unit<0>.dataChannel<71>=psi_out_clk_sel<4>
Project.unit<0>.dataChannel<72>=psi_out_clk_sel<5>
Project.unit<0>.dataChannel<73>=scin_phys<0>
Project.unit<0>.dataChannel<7>=PSI_Dig_Blk_1/CHIP_TMGR/we_out
Project.unit<0>.dataChannel<8>=PSI_Dig_Blk_2/CHIP_TMGR/we_out
Project.unit<0>.dataChannel<9>=PSI_Dig_Blk_0/psi_dec_data_we
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=79
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=psi_dig_read<0>
Project.unit<0>.triggerChannel<0><10>=PSI_Dig_Blk_1/psi_dec_data_we
Project.unit<0>.triggerChannel<0><11>=PSI_Dig_Blk_2/psi_dec_data_we
Project.unit<0>.triggerChannel<0><12>=bypass_token_stack
Project.unit<0>.triggerChannel<0><13>=psi_dig_ctrl<0>
Project.unit<0>.triggerChannel<0><14>=psi_dig_ctrl<1>
Project.unit<0>.triggerChannel<0><15>=psi_dig_ctrl<4>
Project.unit<0>.triggerChannel<0><16>=psi_dig_ctrl<5>
Project.unit<0>.triggerChannel<0><17>=psi_dig_ctrl<6>
Project.unit<0>.triggerChannel<0><18>=psi_dig_ctrl<7>
Project.unit<0>.triggerChannel<0><19>=PSI_Dig_Blk_0/XLXI_6064 mclk_have_data
Project.unit<0>.triggerChannel<0><1>=psi_dig_read<1>
Project.unit<0>.triggerChannel<0><20>=PSI_Dig_Blk_1/XLXI_6064 mclk_have_data
Project.unit<0>.triggerChannel<0><21>=PSI_Dig_Blk_2/XLXI_6064 mclk_have_data
Project.unit<0>.triggerChannel<0><22>=PSI_Dig_Blk_0/XLXI_6064 sm_ready
Project.unit<0>.triggerChannel<0><23>=PSI_Dig_Blk_1/XLXI_6064 sm_ready
Project.unit<0>.triggerChannel<0><24>=PSI_Dig_Blk_2/XLXI_6064 sm_ready
Project.unit<0>.triggerChannel<0><25>=psi_token_in<0>
Project.unit<0>.triggerChannel<0><26>=psi_token_in<1>
Project.unit<0>.triggerChannel<0><27>=psi_token_in<2>
Project.unit<0>.triggerChannel<0><28>=psi_token_out<0>
Project.unit<0>.triggerChannel<0><29>=psi_token_out<1>
Project.unit<0>.triggerChannel<0><2>=psi_dig_read<2>
Project.unit<0>.triggerChannel<0><30>=psi_token_out<2>
Project.unit<0>.triggerChannel<0><31>=EXT_TRIGG
Project.unit<0>.triggerChannel<0><32>=EXT_CLK
Project.unit<0>.triggerChannel<0><33>=psi_extdom_trig
Project.unit<0>.triggerChannel<0><34>=psi_dig_data_delay_inc
Project.unit<0>.triggerChannel<0><35>=psi_dig_data_delay_rst
Project.unit<0>.triggerChannel<0><36>=psi_data_out<0>
Project.unit<0>.triggerChannel<0><37>=psi_data_out<1>
Project.unit<0>.triggerChannel<0><38>=psi_data_out<2>
Project.unit<0>.triggerChannel<0><39>=psi_token_reset_n<0>
Project.unit<0>.triggerChannel<0><3>=PSI_Dig_Blk_0/CHIP_TMGR/have_data
Project.unit<0>.triggerChannel<0><40>=psi_token_reset_n<1>
Project.unit<0>.triggerChannel<0><41>=psi_token_reset_n<2>
Project.unit<0>.triggerChannel<0><42>=error_reset_req<0>
Project.unit<0>.triggerChannel<0><43>=error_reset_req<1>
Project.unit<0>.triggerChannel<0><44>=error_reset_req<2>
Project.unit<0>.triggerChannel<0><45>=TokenStack_vector_0 ovf_flow
Project.unit<0>.triggerChannel<0><46>=TokenStack_vector_1 ovf_flow
Project.unit<0>.triggerChannel<0><47>=TokenStack_vector_2 ovf_flow
Project.unit<0>.triggerChannel<0><48>=PSI_Dig_Blk_0/XLXI_6064 error
Project.unit<0>.triggerChannel<0><49>=PSI_Dig_Blk_1/XLXI_6064 error
Project.unit<0>.triggerChannel<0><4>=PSI_Dig_Blk_1/CHIP_TMGR/have_data
Project.unit<0>.triggerChannel<0><50>=PSI_Dig_Blk_2/XLXI_6064 error
Project.unit<0>.triggerChannel<0><51>=TokenStack_vector_0 count<0>
Project.unit<0>.triggerChannel<0><52>=TokenStack_vector_0 count<1>
Project.unit<0>.triggerChannel<0><53>=TokenStack_vector_0 count<2>
Project.unit<0>.triggerChannel<0><54>=TokenStack_vector_0 count<3>
Project.unit<0>.triggerChannel<0><55>=TokenStack_vector_1 count<0>
Project.unit<0>.triggerChannel<0><56>=TokenStack_vector_1 count<1>
Project.unit<0>.triggerChannel<0><57>=TokenStack_vector_1 count<2>
Project.unit<0>.triggerChannel<0><58>=TokenStack_vector_1 count<3>
Project.unit<0>.triggerChannel<0><59>=TokenStack_vector_2 count<0>
Project.unit<0>.triggerChannel<0><5>=PSI_Dig_Blk_2/CHIP_TMGR/have_data
Project.unit<0>.triggerChannel<0><60>=TokenStack_vector_2 count<1>
Project.unit<0>.triggerChannel<0><61>=TokenStack_vector_2 count<2>
Project.unit<0>.triggerChannel<0><62>=TokenStack_vector_2 count<3>
Project.unit<0>.triggerChannel<0><63>=PSI_CLK0
Project.unit<0>.triggerChannel<0><64>=psi_cmd_sender_dout<0>
Project.unit<0>.triggerChannel<0><65>=psi_cmd_sender_dout<1>
Project.unit<0>.triggerChannel<0><66>=psi_cmd_sender_dout<2>
Project.unit<0>.triggerChannel<0><67>=psi_out_clk_sel<0>
Project.unit<0>.triggerChannel<0><68>=psi_out_clk_sel<1>
Project.unit<0>.triggerChannel<0><69>=psi_out_clk_sel<2>
Project.unit<0>.triggerChannel<0><6>=PSI_Dig_Blk_0/CHIP_TMGR/we_out
Project.unit<0>.triggerChannel<0><70>=psi_out_clk_sel<3>
Project.unit<0>.triggerChannel<0><71>=psi_out_clk_sel<4>
Project.unit<0>.triggerChannel<0><72>=psi_out_clk_sel<5>
Project.unit<0>.triggerChannel<0><73>=scin_phys<0>
Project.unit<0>.triggerChannel<0><74>=MASTER_TRIGGER_MAP
Project.unit<0>.triggerChannel<0><75>=telescope_trigger_en
Project.unit<0>.triggerChannel<0><76>=trig_fifo_empty
Project.unit<0>.triggerChannel<0><77>=trig_fifo_re
Project.unit<0>.triggerChannel<0><78>=trig_fifo_we
Project.unit<0>.triggerChannel<0><79>=
Project.unit<0>.triggerChannel<0><7>=PSI_Dig_Blk_1/CHIP_TMGR/we_out
Project.unit<0>.triggerChannel<0><80>=
Project.unit<0>.triggerChannel<0><81>=
Project.unit<0>.triggerChannel<0><82>=
Project.unit<0>.triggerChannel<0><83>=
Project.unit<0>.triggerChannel<0><84>=
Project.unit<0>.triggerChannel<0><85>=
Project.unit<0>.triggerChannel<0><86>=
Project.unit<0>.triggerChannel<0><87>=
Project.unit<0>.triggerChannel<0><88>=
Project.unit<0>.triggerChannel<0><89>=
Project.unit<0>.triggerChannel<0><8>=PSI_Dig_Blk_2/CHIP_TMGR/we_out
Project.unit<0>.triggerChannel<0><90>=
Project.unit<0>.triggerChannel<0><91>=
Project.unit<0>.triggerChannel<0><92>=
Project.unit<0>.triggerChannel<0><93>=
Project.unit<0>.triggerChannel<0><94>=
Project.unit<0>.triggerChannel<0><95>=
Project.unit<0>.triggerChannel<0><96>=
Project.unit<0>.triggerChannel<0><97>=
Project.unit<0>.triggerChannel<0><98>=
Project.unit<0>.triggerChannel<0><99>=
Project.unit<0>.triggerChannel<0><9>=PSI_Dig_Blk_0/psi_dec_data_we
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=5
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=79
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
