# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/rrivera/otsdaq-firmware/cactus/projects/nim_plus2/top/top.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
