#ChipScope Core Inserter Project File Version 3.0
#Tue Jan 16 11:34:56 CST 2018
Project.device.designInputFile=D\:\\Projects\\Colorado\\digPSI\\DIG_Colorado_captan_plus\\CMS_TB_MASTER_\\GEL_CAPTAN\\TOP_LEVEL_cs.ngc
Project.device.designOutputFile=D\:\\Projects\\Colorado\\digPSI\\DIG_Colorado_captan_plus\\CMS_TB_MASTER_\\GEL_CAPTAN\\TOP_LEVEL_cs.ngc
Project.device.deviceFamily=21
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\Projects\\Colorado\\digPSI\\DIG_Colorado_captan_plus\\CMS_TB_MASTER_\\GEL_CAPTAN\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=*have_data*
Project.filter<11>=*we_out*
Project.filter<12>=*psi_dec*
Project.filter<13>=*psi*
Project.filter<14>=*dig_read*
Project.filter<15>=*we*
Project.filter<16>=*sm_ready*
Project.filter<17>=*_token_*
Project.filter<18>=*token*
Project.filter<1>=*data*
Project.filter<2>=*rx*
Project.filter<3>=*udp*
Project.filter<4>=*is*
Project.filter<5>=*is_*
Project.filter<6>=*RX*
Project.filter<7>=*TX*
Project.filter<8>=*have*
Project.filter<9>=reset
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=MASTER_CLK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=psi_dig_read<0>
Project.unit<0>.dataChannel<10>=PSI_Dig_Blk_1/psi_dec_data_we
Project.unit<0>.dataChannel<11>=PSI_Dig_Blk_2/psi_dec_data_we
Project.unit<0>.dataChannel<12>=bypass_token_stack
Project.unit<0>.dataChannel<13>=psi_dig_ctrl<0>
Project.unit<0>.dataChannel<14>=psi_dig_ctrl<1>
Project.unit<0>.dataChannel<15>=psi_dig_ctrl<4>
Project.unit<0>.dataChannel<16>=psi_dig_ctrl<5>
Project.unit<0>.dataChannel<17>=psi_dig_ctrl<6>
Project.unit<0>.dataChannel<18>=psi_dig_ctrl<7>
Project.unit<0>.dataChannel<19>=PSI_Dig_Blk_0/XLXI_6064 mclk_have_data
Project.unit<0>.dataChannel<1>=psi_dig_read<1>
Project.unit<0>.dataChannel<20>=PSI_Dig_Blk_0/XLXI_6064 sm_ready
Project.unit<0>.dataChannel<21>=PSI_Dig_Blk_1/XLXI_6064 sm_ready
Project.unit<0>.dataChannel<22>=PSI_Dig_Blk_2/XLXI_6064 sm_ready
Project.unit<0>.dataChannel<23>=psi_token_in<0>
Project.unit<0>.dataChannel<24>=psi_token_in<1>
Project.unit<0>.dataChannel<25>=psi_token_in<2>
Project.unit<0>.dataChannel<26>=psi_token_out<0>
Project.unit<0>.dataChannel<27>=reset
Project.unit<0>.dataChannel<28>=psi_extdom_trig
Project.unit<0>.dataChannel<29>=psi_dig_data_delay_inc
Project.unit<0>.dataChannel<2>=psi_dig_read<2>
Project.unit<0>.dataChannel<30>=psi_dig_data_delay_rst
Project.unit<0>.dataChannel<31>=psi_token_reset_n<0>
Project.unit<0>.dataChannel<32>=psi_data_out<0>
Project.unit<0>.dataChannel<33>=PHY_TXD_sig<0>
Project.unit<0>.dataChannel<34>=PHY_TXD_sig<1>
Project.unit<0>.dataChannel<35>=PHY_TXD_sig<2>
Project.unit<0>.dataChannel<36>=PHY_TXD_sig<3>
Project.unit<0>.dataChannel<37>=PHY_TXD_sig<4>
Project.unit<0>.dataChannel<38>=PHY_TXD_sig<5>
Project.unit<0>.dataChannel<39>=PHY_TXD_sig<6>
Project.unit<0>.dataChannel<3>=PSI_Dig_Blk_0/CHIP_TMGR/have_data
Project.unit<0>.dataChannel<40>=PHY_TXD_sig<7>
Project.unit<0>.dataChannel<41>=PHY_TXEN_sig
Project.unit<0>.dataChannel<42>=XLXI_6334 PHY_RXD<0>
Project.unit<0>.dataChannel<43>=XLXI_6334 PHY_RXD<1>
Project.unit<0>.dataChannel<44>=XLXI_6334 PHY_RXD<2>
Project.unit<0>.dataChannel<45>=XLXI_6334 PHY_RXD<3>
Project.unit<0>.dataChannel<46>=XLXI_6334 PHY_RXD<4>
Project.unit<0>.dataChannel<47>=XLXI_6334 PHY_RXD<5>
Project.unit<0>.dataChannel<48>=XLXI_6334 PHY_RXD<6>
Project.unit<0>.dataChannel<49>=XLXI_6334 PHY_RXD<7>
Project.unit<0>.dataChannel<4>=PSI_Dig_Blk_1/CHIP_TMGR/have_data
Project.unit<0>.dataChannel<50>=XLXI_6334 PHY_RX_DV
Project.unit<0>.dataChannel<51>=XLXI_6334 ec_wrapper ethernet_controller is_arp_req_sig
Project.unit<0>.dataChannel<52>=XLXI_6334 ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.dataChannel<53>=XLXI_6334 ec_wrapper ethernet_controller is_ip_packet_sig
Project.unit<0>.dataChannel<54>=XLXI_6334 ec_wrapper ethernet_controller DecipherBlock is_udp_sig
Project.unit<0>.dataChannel<5>=PSI_Dig_Blk_2/CHIP_TMGR/have_data
Project.unit<0>.dataChannel<6>=PSI_Dig_Blk_0/CHIP_TMGR/we_out
Project.unit<0>.dataChannel<7>=PSI_Dig_Blk_1/CHIP_TMGR/we_out
Project.unit<0>.dataChannel<8>=PSI_Dig_Blk_2/CHIP_TMGR/we_out
Project.unit<0>.dataChannel<9>=PSI_Dig_Blk_0/psi_dec_data_we
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=55
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=psi_dig_read<0>
Project.unit<0>.triggerChannel<0><10>=PSI_Dig_Blk_1/psi_dec_data_we
Project.unit<0>.triggerChannel<0><11>=PSI_Dig_Blk_2/psi_dec_data_we
Project.unit<0>.triggerChannel<0><12>=bypass_token_stack
Project.unit<0>.triggerChannel<0><13>=psi_dig_ctrl<0>
Project.unit<0>.triggerChannel<0><14>=psi_dig_ctrl<1>
Project.unit<0>.triggerChannel<0><15>=psi_dig_ctrl<4>
Project.unit<0>.triggerChannel<0><16>=psi_dig_ctrl<5>
Project.unit<0>.triggerChannel<0><17>=psi_dig_ctrl<6>
Project.unit<0>.triggerChannel<0><18>=psi_dig_ctrl<7>
Project.unit<0>.triggerChannel<0><19>=PSI_Dig_Blk_0/XLXI_6064 mclk_have_data
Project.unit<0>.triggerChannel<0><1>=psi_dig_read<1>
Project.unit<0>.triggerChannel<0><20>=PSI_Dig_Blk_0/XLXI_6064 sm_ready
Project.unit<0>.triggerChannel<0><21>=PSI_Dig_Blk_1/XLXI_6064 sm_ready
Project.unit<0>.triggerChannel<0><22>=PSI_Dig_Blk_2/XLXI_6064 sm_ready
Project.unit<0>.triggerChannel<0><23>=psi_token_in<0>
Project.unit<0>.triggerChannel<0><24>=psi_token_in<1>
Project.unit<0>.triggerChannel<0><25>=psi_token_in<2>
Project.unit<0>.triggerChannel<0><26>=psi_token_out<0>
Project.unit<0>.triggerChannel<0><27>=reset
Project.unit<0>.triggerChannel<0><28>=psi_extdom_trig
Project.unit<0>.triggerChannel<0><29>=psi_dig_data_delay_inc
Project.unit<0>.triggerChannel<0><2>=psi_dig_read<2>
Project.unit<0>.triggerChannel<0><30>=psi_dig_data_delay_rst
Project.unit<0>.triggerChannel<0><31>=psi_token_reset_n<0>
Project.unit<0>.triggerChannel<0><32>=psi_data_out<0>
Project.unit<0>.triggerChannel<0><33>=PHY_TXD_sig<0>
Project.unit<0>.triggerChannel<0><34>=PHY_TXD_sig<1>
Project.unit<0>.triggerChannel<0><35>=PHY_TXD_sig<2>
Project.unit<0>.triggerChannel<0><36>=PHY_TXD_sig<3>
Project.unit<0>.triggerChannel<0><37>=PHY_TXD_sig<4>
Project.unit<0>.triggerChannel<0><38>=PHY_TXD_sig<5>
Project.unit<0>.triggerChannel<0><39>=PHY_TXD_sig<6>
Project.unit<0>.triggerChannel<0><3>=PSI_Dig_Blk_0/CHIP_TMGR/have_data
Project.unit<0>.triggerChannel<0><40>=PHY_TXD_sig<7>
Project.unit<0>.triggerChannel<0><41>=PHY_TXEN_sig
Project.unit<0>.triggerChannel<0><42>=XLXI_6334 PHY_RXD<0>
Project.unit<0>.triggerChannel<0><43>=XLXI_6334 PHY_RXD<1>
Project.unit<0>.triggerChannel<0><44>=XLXI_6334 PHY_RXD<2>
Project.unit<0>.triggerChannel<0><45>=XLXI_6334 PHY_RXD<3>
Project.unit<0>.triggerChannel<0><46>=XLXI_6334 PHY_RXD<4>
Project.unit<0>.triggerChannel<0><47>=XLXI_6334 PHY_RXD<5>
Project.unit<0>.triggerChannel<0><48>=XLXI_6334 PHY_RXD<6>
Project.unit<0>.triggerChannel<0><49>=XLXI_6334 PHY_RXD<7>
Project.unit<0>.triggerChannel<0><4>=PSI_Dig_Blk_1/CHIP_TMGR/have_data
Project.unit<0>.triggerChannel<0><50>=XLXI_6334 PHY_RX_DV
Project.unit<0>.triggerChannel<0><51>=XLXI_6334 ec_wrapper ethernet_controller is_arp_req_sig
Project.unit<0>.triggerChannel<0><52>=XLXI_6334 ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.triggerChannel<0><53>=XLXI_6334 ec_wrapper ethernet_controller is_ip_packet_sig
Project.unit<0>.triggerChannel<0><54>=XLXI_6334 ec_wrapper ethernet_controller DecipherBlock is_udp_sig
Project.unit<0>.triggerChannel<0><5>=PSI_Dig_Blk_2/CHIP_TMGR/have_data
Project.unit<0>.triggerChannel<0><6>=PSI_Dig_Blk_0/CHIP_TMGR/we_out
Project.unit<0>.triggerChannel<0><7>=PSI_Dig_Blk_1/CHIP_TMGR/we_out
Project.unit<0>.triggerChannel<0><8>=PSI_Dig_Blk_2/CHIP_TMGR/we_out
Project.unit<0>.triggerChannel<0><9>=PSI_Dig_Blk_0/psi_dec_data_we
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=5
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=55
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
