set_property SRC_FILE_INFO {cfile:/home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source_x/top/top.srcs/constrs_1/new/top.xdc rfile:../../../top.srcs/constrs_1/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0_0 ila
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0_0]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/clk [get_nets [list MASTER_CLK]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0_0/probe0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe0 [get_nets [list {reg_rate[0]} {reg_rate[1]} {reg_rate[2]} {reg_rate[3]} {reg_rate[4]} {reg_rate[5]} {reg_rate[6]} {reg_rate[7]} {reg_rate[8]} {reg_rate[9]} {reg_rate[10]} {reg_rate[11]} {reg_rate[12]} {reg_rate[13]} {reg_rate[14]} {reg_rate[15]} {reg_rate[16]} {reg_rate[17]} {reg_rate[18]} {reg_rate[19]} {reg_rate[20]} {reg_rate[21]} {reg_rate[22]} {reg_rate[23]} {reg_rate[24]} {reg_rate[25]} {reg_rate[26]} {reg_rate[27]} {reg_rate[28]} {reg_rate[29]} {reg_rate[30]} {reg_rate[31]} {reg_rate[32]} {reg_rate[33]} {reg_rate[34]} {reg_rate[35]} {reg_rate[36]} {reg_rate[37]} {reg_rate[38]} {reg_rate[39]} {reg_rate[40]} {reg_rate[41]} {reg_rate[42]} {reg_rate[43]} {reg_rate[44]} {reg_rate[45]} {reg_rate[46]} {reg_rate[47]} {reg_rate[48]} {reg_rate[49]} {reg_rate[50]} {reg_rate[51]} {reg_rate[52]} {reg_rate[53]} {reg_rate[54]} {reg_rate[55]} {reg_rate[56]} {reg_rate[57]} {reg_rate[58]} {reg_rate[59]} {reg_rate[60]} {reg_rate[61]} {reg_rate[62]} {reg_rate[63]}]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe1 [get_nets [list {rx_addr[0]} {rx_addr[1]} {rx_addr[2]} {rx_addr[3]} {rx_addr[4]} {rx_addr[5]} {rx_addr[6]} {rx_addr[7]} {rx_addr[8]} {rx_addr[9]} {rx_addr[10]} {rx_addr[11]} {rx_addr[12]} {rx_addr[13]} {rx_addr[14]} {rx_addr[15]} {rx_addr[16]} {rx_addr[17]} {rx_addr[18]} {rx_addr[19]} {rx_addr[20]} {rx_addr[21]} {rx_addr[22]} {rx_addr[23]} {rx_addr[24]} {rx_addr[25]} {rx_addr[26]} {rx_addr[27]} {rx_addr[28]} {rx_addr[29]} {rx_addr[30]} {rx_addr[31]}]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0_0/probe2]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe2 [get_nets [list {tx_data[0]} {tx_data[1]} {tx_data[2]} {tx_data[3]} {tx_data[4]} {tx_data[5]} {tx_data[6]} {tx_data[7]} {tx_data[8]} {tx_data[9]} {tx_data[10]} {tx_data[11]} {tx_data[12]} {tx_data[13]} {tx_data[14]} {tx_data[15]} {tx_data[16]} {tx_data[17]} {tx_data[18]} {tx_data[19]} {tx_data[20]} {tx_data[21]} {tx_data[22]} {tx_data[23]} {tx_data[24]} {tx_data[25]} {tx_data[26]} {tx_data[27]} {tx_data[28]} {tx_data[29]} {tx_data[30]} {tx_data[31]} {tx_data[32]} {tx_data[33]} {tx_data[34]} {tx_data[35]} {tx_data[36]} {tx_data[37]} {tx_data[38]} {tx_data[39]} {tx_data[40]} {tx_data[41]} {tx_data[42]} {tx_data[43]} {tx_data[44]} {tx_data[45]} {tx_data[46]} {tx_data[47]} {tx_data[48]} {tx_data[49]} {tx_data[50]} {tx_data[51]} {tx_data[52]} {tx_data[53]} {tx_data[54]} {tx_data[55]} {tx_data[56]} {tx_data[57]} {tx_data[58]} {tx_data[59]} {tx_data[60]} {tx_data[61]} {tx_data[62]} {tx_data[63]}]]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe3]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe3 [get_nets [list {PHY_TXD_sig[0]} {PHY_TXD_sig[1]} {PHY_TXD_sig[2]} {PHY_TXD_sig[3]} {PHY_TXD_sig[4]} {PHY_TXD_sig[5]} {PHY_TXD_sig[6]} {PHY_TXD_sig[7]}]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0_0/probe4]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe4 [get_nets [list {delay_cnt[0]} {delay_cnt[1]} {delay_cnt[2]} {delay_cnt[3]} {delay_cnt[4]} {delay_cnt[5]} {delay_cnt[6]} {delay_cnt[7]} {delay_cnt[8]} {delay_cnt[9]} {delay_cnt[10]} {delay_cnt[11]} {delay_cnt[12]} {delay_cnt[13]} {delay_cnt[14]} {delay_cnt[15]} {delay_cnt[16]} {delay_cnt[17]} {delay_cnt[18]} {delay_cnt[19]} {delay_cnt[20]} {delay_cnt[21]} {delay_cnt[22]} {delay_cnt[23]} {delay_cnt[24]} {delay_cnt[25]} {delay_cnt[26]} {delay_cnt[27]} {delay_cnt[28]} {delay_cnt[29]} {delay_cnt[30]} {delay_cnt[31]} {delay_cnt[32]} {delay_cnt[33]} {delay_cnt[34]} {delay_cnt[35]} {delay_cnt[36]} {delay_cnt[37]} {delay_cnt[38]} {delay_cnt[39]} {delay_cnt[40]} {delay_cnt[41]} {delay_cnt[42]} {delay_cnt[43]} {delay_cnt[44]} {delay_cnt[45]} {delay_cnt[46]} {delay_cnt[47]} {delay_cnt[48]} {delay_cnt[49]} {delay_cnt[50]} {delay_cnt[51]} {delay_cnt[52]} {delay_cnt[53]} {delay_cnt[54]} {delay_cnt[55]} {delay_cnt[56]} {delay_cnt[57]} {delay_cnt[58]} {delay_cnt[59]} {delay_cnt[60]} {delay_cnt[61]} {delay_cnt[62]} {delay_cnt[63]}]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0_0/probe5]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe5 [get_nets [list {rx_data[0]} {rx_data[1]} {rx_data[2]} {rx_data[3]} {rx_data[4]} {rx_data[5]} {rx_data[6]} {rx_data[7]} {rx_data[8]} {rx_data[9]} {rx_data[10]} {rx_data[11]} {rx_data[12]} {rx_data[13]} {rx_data[14]} {rx_data[15]} {rx_data[16]} {rx_data[17]} {rx_data[18]} {rx_data[19]} {rx_data[20]} {rx_data[21]} {rx_data[22]} {rx_data[23]} {rx_data[24]} {rx_data[25]} {rx_data[26]} {rx_data[27]} {rx_data[28]} {rx_data[29]} {rx_data[30]} {rx_data[31]} {rx_data[32]} {rx_data[33]} {rx_data[34]} {rx_data[35]} {rx_data[36]} {rx_data[37]} {rx_data[38]} {rx_data[39]} {rx_data[40]} {rx_data[41]} {rx_data[42]} {rx_data[43]} {rx_data[44]} {rx_data[45]} {rx_data[46]} {rx_data[47]} {rx_data[48]} {rx_data[49]} {rx_data[50]} {rx_data[51]} {rx_data[52]} {rx_data[53]} {rx_data[54]} {rx_data[55]} {rx_data[56]} {rx_data[57]} {rx_data[58]} {rx_data[59]} {rx_data[60]} {rx_data[61]} {rx_data[62]} {rx_data[63]}]]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0_0/probe6]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe6 [get_nets [list {data_cnt[0]} {data_cnt[1]} {data_cnt[2]} {data_cnt[3]} {data_cnt[4]} {data_cnt[5]} {data_cnt[6]} {data_cnt[7]} {data_cnt[8]} {data_cnt[9]} {data_cnt[10]} {data_cnt[11]} {data_cnt[12]} {data_cnt[13]} {data_cnt[14]} {data_cnt[15]} {data_cnt[16]} {data_cnt[17]} {data_cnt[18]} {data_cnt[19]} {data_cnt[20]} {data_cnt[21]} {data_cnt[22]} {data_cnt[23]} {data_cnt[24]} {data_cnt[25]} {data_cnt[26]} {data_cnt[27]} {data_cnt[28]} {data_cnt[29]} {data_cnt[30]} {data_cnt[31]}]]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0_0/probe7]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe7 [get_nets [list {cnt[0]} {cnt[1]} {cnt[2]}]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0_0/probe8]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe8 [get_nets [list {b_data[0]} {b_data[1]} {b_data[2]} {b_data[3]} {b_data[4]} {b_data[5]} {b_data[6]} {b_data[7]} {b_data[8]} {b_data[9]} {b_data[10]} {b_data[11]} {b_data[12]} {b_data[13]} {b_data[14]} {b_data[15]} {b_data[16]} {b_data[17]} {b_data[18]} {b_data[19]} {b_data[20]} {b_data[21]} {b_data[22]} {b_data[23]} {b_data[24]} {b_data[25]} {b_data[26]} {b_data[27]} {b_data[28]} {b_data[29]} {b_data[30]} {b_data[31]} {b_data[32]} {b_data[33]} {b_data[34]} {b_data[35]} {b_data[36]} {b_data[37]} {b_data[38]} {b_data[39]} {b_data[40]} {b_data[41]} {b_data[42]} {b_data[43]} {b_data[44]} {b_data[45]} {b_data[46]} {b_data[47]} {b_data[48]} {b_data[49]} {b_data[50]} {b_data[51]} {b_data[52]} {b_data[53]} {b_data[54]} {b_data[55]} {b_data[56]} {b_data[57]} {b_data[58]} {b_data[59]} {b_data[60]} {b_data[61]} {b_data[62]} {b_data[63]}]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0_0/probe9]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe9 [get_nets [list {reg_cnt[0]} {reg_cnt[1]} {reg_cnt[2]} {reg_cnt[3]} {reg_cnt[4]} {reg_cnt[5]} {reg_cnt[6]} {reg_cnt[7]} {reg_cnt[8]} {reg_cnt[9]} {reg_cnt[10]} {reg_cnt[11]} {reg_cnt[12]} {reg_cnt[13]} {reg_cnt[14]} {reg_cnt[15]} {reg_cnt[16]} {reg_cnt[17]} {reg_cnt[18]} {reg_cnt[19]} {reg_cnt[20]} {reg_cnt[21]} {reg_cnt[22]} {reg_cnt[23]} {reg_cnt[24]} {reg_cnt[25]} {reg_cnt[26]} {reg_cnt[27]} {reg_cnt[28]} {reg_cnt[29]} {reg_cnt[30]} {reg_cnt[31]} {reg_cnt[32]} {reg_cnt[33]} {reg_cnt[34]} {reg_cnt[35]} {reg_cnt[36]} {reg_cnt[37]} {reg_cnt[38]} {reg_cnt[39]} {reg_cnt[40]} {reg_cnt[41]} {reg_cnt[42]} {reg_cnt[43]} {reg_cnt[44]} {reg_cnt[45]} {reg_cnt[46]} {reg_cnt[47]} {reg_cnt[48]} {reg_cnt[49]} {reg_cnt[50]} {reg_cnt[51]} {reg_cnt[52]} {reg_cnt[53]} {reg_cnt[54]} {reg_cnt[55]} {reg_cnt[56]} {reg_cnt[57]} {reg_cnt[58]} {reg_cnt[59]} {reg_cnt[60]} {reg_cnt[61]} {reg_cnt[62]} {reg_cnt[63]}]]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0_0/probe10]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe10 [get_nets [list {GMII_RXD_0_sig[0]} {GMII_RXD_0_sig[1]} {GMII_RXD_0_sig[2]} {GMII_RXD_0_sig[3]} {GMII_RXD_0_sig[4]} {GMII_RXD_0_sig[5]} {GMII_RXD_0_sig[6]} {GMII_RXD_0_sig[7]}]]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe11]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe11 [get_nets [list b_data_we]]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe12]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe12 [get_nets [list GMII_RX_DV_0_sig]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe13]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe13 [get_nets [list PHY_TXEN_sig]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0_0 probe
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0_0/probe14]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0_0/probe14 [get_nets [list rx_wren]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets MASTER_CLK]
