#ChipScope Core Inserter Project File Version 3.0
#Wed May 30 16:42:08 CDT 2018
Project.device.designInputFile=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_slave_ots/slave/top_cs.ngc
Project.device.designOutputFile=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_slave_ots/slave/top_cs.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_slave_ots/slave/_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*delta*
Project.filter<10>=*dcm_bco_div*
Project.filter<11>=*clk_q*
Project.filter<12>=*reset*
Project.filter<13>=*bcoclk_reset*
Project.filter<14>=*bcoclk_*
Project.filter<15>=*bco_*
Project.filter<16>=*local_bc*
Project.filter<17>=*repeat*
Project.filter<18>=*watch*
Project.filter<1>=
Project.filter<2>=*local_bco*
Project.filter<3>=*bco*
Project.filter<4>=*local*
Project.filter<5>=*delta
Project.filter<6>=*READ_EN*
Project.filter<7>=*full*
Project.filter<8>=*locked*
Project.filter<9>=*lost*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=GMII_RXCLK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=masked_rx_wren2
Project.unit<0>.dataChannel<100>=local_read_done
Project.unit<0>.dataChannel<101>=local_start<0>
Project.unit<0>.dataChannel<102>=local_trigger<0>
Project.unit<0>.dataChannel<103>=local_bco_clk<0>
Project.unit<0>.dataChannel<104>=local_start_count<0>
Project.unit<0>.dataChannel<105>=local_start_count<1>
Project.unit<0>.dataChannel<106>=local_start_count<2>
Project.unit<0>.dataChannel<107>=local_start_count<3>
Project.unit<0>.dataChannel<108>=local_read_actually_done
Project.unit<0>.dataChannel<109>=local_bco_time<0>
Project.unit<0>.dataChannel<10>=eth_interface data_manager_blk TX_CTRL_FIFO wr_en
Project.unit<0>.dataChannel<110>=local_bco_time<1>
Project.unit<0>.dataChannel<111>=local_bco_time<2>
Project.unit<0>.dataChannel<112>=local_bco_time<3>
Project.unit<0>.dataChannel<113>=local_bco_zero
Project.unit<0>.dataChannel<114>=local_bco_zero_cnt<0>
Project.unit<0>.dataChannel<115>=local_bco_zero_cnt<1>
Project.unit<0>.dataChannel<116>=local_bco_zero_cnt<2>
Project.unit<0>.dataChannel<117>=local_bco_zero_cnt<3>
Project.unit<0>.dataChannel<118>=ext_cmd
Project.unit<0>.dataChannel<119>=START
Project.unit<0>.dataChannel<11>=eth_interface b_enable
Project.unit<0>.dataChannel<120>=strip_clocks_locked
Project.unit<0>.dataChannel<121>=strip_imp stripclk_imp bcocounter_imp sclr
Project.unit<0>.dataChannel<122>=strip_imp stripclk_imp dcm_fbco_locked
Project.unit<0>.dataChannel<123>=strip_imp stripclk_imp locked<0>
Project.unit<0>.dataChannel<124>=strip_imp stripclk_imp locked<1>
Project.unit<0>.dataChannel<125>=strip_imp stripclk_imp clk_z
Project.unit<0>.dataChannel<126>=strip_imp stripclk_imp fcbo_watchdog_reset
Project.unit<0>.dataChannel<127>=strip_imp stripclk_imp fcbo_watchdog_reset_sig
Project.unit<0>.dataChannel<128>=strip_imp strip_csr<3>
Project.unit<0>.dataChannel<129>=strip_imp strip_csr<4>
Project.unit<0>.dataChannel<12>=b_data_we
Project.unit<0>.dataChannel<130>=strip_imp strip_csr<5>
Project.unit<0>.dataChannel<131>=strip_imp strip_csr<6>
Project.unit<0>.dataChannel<132>=strip_imp strip_csr<7>
Project.unit<0>.dataChannel<133>=strip_imp strip_csr<8>
Project.unit<0>.dataChannel<134>=strip_imp strip_csr<9>
Project.unit<0>.dataChannel<135>=strip_imp strip_csr<10>
Project.unit<0>.dataChannel<136>=strip_imp strip_csr<11>
Project.unit<0>.dataChannel<137>=strip_imp strip_csr<12>
Project.unit<0>.dataChannel<138>=strip_imp strip_csr<13>
Project.unit<0>.dataChannel<139>=strip_imp strip_csr<14>
Project.unit<0>.dataChannel<13>=b_data<0>
Project.unit<0>.dataChannel<140>=strip_imp strip_csr<15>
Project.unit<0>.dataChannel<141>=strip_imp strip_csr<16>
Project.unit<0>.dataChannel<142>=strip_imp strip_csr<17>
Project.unit<0>.dataChannel<143>=strip_imp strip_csr<18>
Project.unit<0>.dataChannel<144>=strip_imp strip_csr<20>
Project.unit<0>.dataChannel<145>=strip_imp strip_csr<21>
Project.unit<0>.dataChannel<146>=strip_imp strip_csr<23>
Project.unit<0>.dataChannel<147>=strip_imp strip_csr<24>
Project.unit<0>.dataChannel<148>=strip_imp strip_csr<25>
Project.unit<0>.dataChannel<149>=strip_imp strip_csr<26>
Project.unit<0>.dataChannel<14>=b_data<1>
Project.unit<0>.dataChannel<150>=strip_imp strip_csr<27>
Project.unit<0>.dataChannel<151>=strip_imp strip_csr<28>
Project.unit<0>.dataChannel<152>=strip_imp strip_csr<31>
Project.unit<0>.dataChannel<153>=strip_busy
Project.unit<0>.dataChannel<154>=strip_ready
Project.unit<0>.dataChannel<155>=strip_imp striptbm_imp TOKEN_IN
Project.unit<0>.dataChannel<156>=strip_imp striptbm_imp TOKEN_OUT
Project.unit<0>.dataChannel<157>=strip_imp striptbm_imp STATE_FSM_FFd2
Project.unit<0>.dataChannel<158>=strip_imp striptbm_imp STATE_FSM_FFd1
Project.unit<0>.dataChannel<159>=strip_imp striptbm_imp DATA_AVAILABLE
Project.unit<0>.dataChannel<15>=b_data<2>
Project.unit<0>.dataChannel<160>=strip_imp striptbm_imp SENT_BCO
Project.unit<0>.dataChannel<161>=strip_imp G[0].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.dataChannel<162>=strip_imp G[0].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.dataChannel<163>=strip_imp G[1].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.dataChannel<164>=strip_imp G[1].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.dataChannel<165>=strip_imp G[2].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.dataChannel<166>=strip_imp G[2].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.dataChannel<167>=strip_imp G[3].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.dataChannel<168>=strip_imp G[3].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.dataChannel<169>=strip_imp G[4].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.dataChannel<16>=b_data<3>
Project.unit<0>.dataChannel<170>=strip_imp G[4].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.dataChannel<171>=strip_imp G[5].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.dataChannel<172>=strip_imp G[5].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.dataChannel<173>=strip_imp G[0].strip_fifo_imp READ_ENABLE
Project.unit<0>.dataChannel<174>=strip_imp G[1].strip_fifo_imp READ_ENABLE
Project.unit<0>.dataChannel<175>=strip_imp G[2].strip_fifo_imp READ_ENABLE
Project.unit<0>.dataChannel<176>=strip_imp G[3].strip_fifo_imp READ_ENABLE
Project.unit<0>.dataChannel<177>=strip_imp G[4].strip_fifo_imp READ_ENABLE
Project.unit<0>.dataChannel<178>=strip_imp G[5].strip_fifo_imp READ_ENABLE
Project.unit<0>.dataChannel<179>=strip_imp stripclk_imp bcoclk_release
Project.unit<0>.dataChannel<17>=b_data<4>
Project.unit<0>.dataChannel<180>=strip_imp stripclk_imp reset
Project.unit<0>.dataChannel<181>=strip_imp stripclk_imp clk_q
Project.unit<0>.dataChannel<182>=local_clock_lock_lost<0>
Project.unit<0>.dataChannel<183>=strip_imp stripclk_imp clkz_dcm_locked
Project.unit<0>.dataChannel<18>=b_data<5>
Project.unit<0>.dataChannel<19>=b_data<6>
Project.unit<0>.dataChannel<1>=eth_interface data_manager_blk TX_DATA_FIFO rd_en
Project.unit<0>.dataChannel<20>=b_data<7>
Project.unit<0>.dataChannel<21>=eth_interface ec_wrapper ethernet_controller is_arp_req_sig
Project.unit<0>.dataChannel<22>=eth_interface ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.dataChannel<23>=eth_interface ec_wrapper ethernet_controller udp_data_valid
Project.unit<0>.dataChannel<24>=PHY_TXEN_sig
Project.unit<0>.dataChannel<25>=tx_rden
Project.unit<0>.dataChannel<26>=local_stripdata_repeat
Project.unit<0>.dataChannel<27>=strip_imp G[0].chipserdes0_imp ALIGNED
Project.unit<0>.dataChannel<28>=strip_imp G[0].chipserdes0_imp DATA_VALID
Project.unit<0>.dataChannel<29>=strip_imp G[0].chipserdes1_imp ALIGNED
Project.unit<0>.dataChannel<2>=eth_interface data_manager_blk TX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.dataChannel<30>=strip_imp G[0].chipserdes1_imp DATA_VALID
Project.unit<0>.dataChannel<31>=strip_imp G[0].chipserdes2_imp ALIGNED
Project.unit<0>.dataChannel<32>=strip_imp G[0].chipserdes2_imp DATA_VALID
Project.unit<0>.dataChannel<33>=strip_imp G[0].chipserdes3_imp ALIGNED
Project.unit<0>.dataChannel<34>=strip_imp G[0].chipserdes3_imp DATA_VALID
Project.unit<0>.dataChannel<35>=strip_imp G[0].chipserdes4_imp ALIGNED
Project.unit<0>.dataChannel<36>=strip_imp G[0].chipserdes4_imp DATA_VALID
Project.unit<0>.dataChannel<37>=strip_imp G[1].chipserdes0_imp ALIGNED
Project.unit<0>.dataChannel<38>=strip_imp G[1].chipserdes0_imp DATA_VALID
Project.unit<0>.dataChannel<39>=strip_imp G[1].chipserdes1_imp ALIGNED
Project.unit<0>.dataChannel<3>=eth_interface data_manager_blk TX_DATA_FIFO wr_en
Project.unit<0>.dataChannel<40>=strip_imp G[1].chipserdes1_imp DATA_VALID
Project.unit<0>.dataChannel<41>=strip_imp G[1].chipserdes2_imp ALIGNED
Project.unit<0>.dataChannel<42>=strip_imp G[1].chipserdes2_imp DATA_VALID
Project.unit<0>.dataChannel<43>=strip_imp G[1].chipserdes3_imp ALIGNED
Project.unit<0>.dataChannel<44>=strip_imp G[1].chipserdes3_imp DATA_VALID
Project.unit<0>.dataChannel<45>=strip_imp G[1].chipserdes4_imp ALIGNED
Project.unit<0>.dataChannel<46>=strip_imp G[1].chipserdes4_imp DATA_VALID
Project.unit<0>.dataChannel<47>=strip_imp G[2].chipserdes0_imp ALIGNED
Project.unit<0>.dataChannel<48>=strip_imp G[2].chipserdes0_imp DATA_VALID
Project.unit<0>.dataChannel<49>=strip_imp G[2].chipserdes1_imp ALIGNED
Project.unit<0>.dataChannel<4>=eth_interface data_manager_blk RX_DATA_FIFO rd_en
Project.unit<0>.dataChannel<50>=strip_imp G[2].chipserdes1_imp DATA_VALID
Project.unit<0>.dataChannel<51>=strip_imp G[2].chipserdes2_imp ALIGNED
Project.unit<0>.dataChannel<52>=strip_imp G[2].chipserdes2_imp DATA_VALID
Project.unit<0>.dataChannel<53>=strip_imp G[2].chipserdes3_imp ALIGNED
Project.unit<0>.dataChannel<54>=strip_imp G[2].chipserdes3_imp DATA_VALID
Project.unit<0>.dataChannel<55>=strip_imp G[2].chipserdes4_imp ALIGNED
Project.unit<0>.dataChannel<56>=strip_imp G[2].chipserdes4_imp DATA_VALID
Project.unit<0>.dataChannel<57>=strip_imp G[3].chipserdes0_imp ALIGNED
Project.unit<0>.dataChannel<58>=strip_imp G[3].chipserdes0_imp DATA_VALID
Project.unit<0>.dataChannel<59>=strip_imp G[3].chipserdes1_imp ALIGNED
Project.unit<0>.dataChannel<5>=eth_interface data_manager_blk RX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.dataChannel<60>=strip_imp G[3].chipserdes1_imp DATA_VALID
Project.unit<0>.dataChannel<61>=strip_imp G[3].chipserdes2_imp ALIGNED
Project.unit<0>.dataChannel<62>=strip_imp G[3].chipserdes2_imp DATA_VALID
Project.unit<0>.dataChannel<63>=strip_imp G[3].chipserdes3_imp ALIGNED
Project.unit<0>.dataChannel<64>=strip_imp G[3].chipserdes3_imp DATA_VALID
Project.unit<0>.dataChannel<65>=strip_imp G[3].chipserdes4_imp ALIGNED
Project.unit<0>.dataChannel<66>=strip_imp G[3].chipserdes4_imp DATA_VALID
Project.unit<0>.dataChannel<67>=strip_imp G[4].chipserdes0_imp ALIGNED
Project.unit<0>.dataChannel<68>=strip_imp G[4].chipserdes0_imp DATA_VALID
Project.unit<0>.dataChannel<69>=strip_imp G[4].chipserdes1_imp ALIGNED
Project.unit<0>.dataChannel<6>=eth_interface data_manager_blk RX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwss.wsts/ram_full_i
Project.unit<0>.dataChannel<70>=strip_imp G[4].chipserdes1_imp DATA_VALID
Project.unit<0>.dataChannel<71>=strip_imp G[4].chipserdes2_imp ALIGNED
Project.unit<0>.dataChannel<72>=strip_imp G[4].chipserdes2_imp DATA_VALID
Project.unit<0>.dataChannel<73>=strip_imp G[4].chipserdes3_imp ALIGNED
Project.unit<0>.dataChannel<74>=strip_imp G[4].chipserdes3_imp DATA_VALID
Project.unit<0>.dataChannel<75>=strip_imp G[4].chipserdes4_imp ALIGNED
Project.unit<0>.dataChannel<76>=strip_imp G[4].chipserdes4_imp DATA_VALID
Project.unit<0>.dataChannel<77>=strip_imp G[5].chipserdes0_imp ALIGNED
Project.unit<0>.dataChannel<78>=strip_imp G[5].chipserdes0_imp DATA_VALID
Project.unit<0>.dataChannel<79>=strip_imp G[5].chipserdes1_imp ALIGNED
Project.unit<0>.dataChannel<7>=eth_interface data_manager_blk RX_DATA_FIFO wr_en
Project.unit<0>.dataChannel<80>=strip_imp G[5].chipserdes1_imp DATA_VALID
Project.unit<0>.dataChannel<81>=strip_imp G[5].chipserdes2_imp ALIGNED
Project.unit<0>.dataChannel<82>=strip_imp G[5].chipserdes2_imp DATA_VALID
Project.unit<0>.dataChannel<83>=strip_imp G[5].chipserdes3_imp ALIGNED
Project.unit<0>.dataChannel<84>=strip_imp G[5].chipserdes3_imp DATA_VALID
Project.unit<0>.dataChannel<85>=strip_imp G[5].chipserdes4_imp ALIGNED
Project.unit<0>.dataChannel<86>=strip_imp G[5].chipserdes4_imp DATA_VALID
Project.unit<0>.dataChannel<87>=stackGen[0].fifo_imp full
Project.unit<0>.dataChannel<88>=stackGen[0].fifo_imp rd_en
Project.unit<0>.dataChannel<89>=stackGen[0].fifo_imp wr_en
Project.unit<0>.dataChannel<8>=eth_interface data_manager_blk TX_CTRL_FIFO rd_en
Project.unit<0>.dataChannel<90>=strip_imp trigproc_imp trigger_count_enable
Project.unit<0>.dataChannel<91>=strip_imp trigproc_imp fifo_imp din<4>
Project.unit<0>.dataChannel<92>=strip_imp trigproc_imp fifo_imp din<5>
Project.unit<0>.dataChannel<93>=strip_imp trigproc_imp fifo_imp din<6>
Project.unit<0>.dataChannel<94>=strip_imp trigproc_imp fifo_imp din<7>
Project.unit<0>.dataChannel<95>=strip_imp trigproc_imp fifo_imp wr_en
Project.unit<0>.dataChannel<96>=strip_imp trigproc_imp fifo_imp rd_en
Project.unit<0>.dataChannel<97>=strip_imp trigproc_imp fifo_imp full
Project.unit<0>.dataChannel<98>=strip_imp latched_trig
Project.unit<0>.dataChannel<99>=local_data_ready
Project.unit<0>.dataChannel<9>=eth_interface data_manager_blk TX_CTRL_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.dataDepth=512
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=200
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=false
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=masked_rx_wren2
Project.unit<0>.triggerChannel<0><100>=local_read_done
Project.unit<0>.triggerChannel<0><101>=local_start<0>
Project.unit<0>.triggerChannel<0><102>=local_trigger<0>
Project.unit<0>.triggerChannel<0><103>=local_bco_clk<0>
Project.unit<0>.triggerChannel<0><104>=local_start_count<0>
Project.unit<0>.triggerChannel<0><105>=local_start_count<1>
Project.unit<0>.triggerChannel<0><106>=local_start_count<2>
Project.unit<0>.triggerChannel<0><107>=local_start_count<3>
Project.unit<0>.triggerChannel<0><108>=local_read_actually_done
Project.unit<0>.triggerChannel<0><109>=local_bco_time<0>
Project.unit<0>.triggerChannel<0><10>=eth_interface data_manager_blk TX_CTRL_FIFO wr_en
Project.unit<0>.triggerChannel<0><110>=local_bco_time<1>
Project.unit<0>.triggerChannel<0><111>=local_bco_time<2>
Project.unit<0>.triggerChannel<0><112>=local_bco_time<3>
Project.unit<0>.triggerChannel<0><113>=local_bco_zero
Project.unit<0>.triggerChannel<0><114>=local_bco_zero_cnt<0>
Project.unit<0>.triggerChannel<0><115>=local_bco_zero_cnt<1>
Project.unit<0>.triggerChannel<0><116>=local_bco_zero_cnt<2>
Project.unit<0>.triggerChannel<0><117>=local_bco_zero_cnt<3>
Project.unit<0>.triggerChannel<0><118>=ext_cmd
Project.unit<0>.triggerChannel<0><119>=START
Project.unit<0>.triggerChannel<0><11>=eth_interface b_enable
Project.unit<0>.triggerChannel<0><120>=strip_clocks_locked
Project.unit<0>.triggerChannel<0><121>=strip_imp stripclk_imp bcocounter_imp sclr
Project.unit<0>.triggerChannel<0><122>=strip_imp stripclk_imp dcm_fbco_locked
Project.unit<0>.triggerChannel<0><123>=strip_imp stripclk_imp locked<0>
Project.unit<0>.triggerChannel<0><124>=strip_imp stripclk_imp locked<1>
Project.unit<0>.triggerChannel<0><125>=strip_imp stripclk_imp clk_z
Project.unit<0>.triggerChannel<0><126>=strip_imp stripclk_imp fcbo_watchdog_reset
Project.unit<0>.triggerChannel<0><127>=strip_imp stripclk_imp fcbo_watchdog_reset_sig
Project.unit<0>.triggerChannel<0><128>=strip_imp strip_csr<3>
Project.unit<0>.triggerChannel<0><129>=strip_imp strip_csr<4>
Project.unit<0>.triggerChannel<0><12>=b_data_we
Project.unit<0>.triggerChannel<0><130>=strip_imp strip_csr<5>
Project.unit<0>.triggerChannel<0><131>=strip_imp strip_csr<6>
Project.unit<0>.triggerChannel<0><132>=strip_imp strip_csr<7>
Project.unit<0>.triggerChannel<0><133>=strip_imp strip_csr<8>
Project.unit<0>.triggerChannel<0><134>=strip_imp strip_csr<9>
Project.unit<0>.triggerChannel<0><135>=strip_imp strip_csr<10>
Project.unit<0>.triggerChannel<0><136>=strip_imp strip_csr<11>
Project.unit<0>.triggerChannel<0><137>=strip_imp strip_csr<12>
Project.unit<0>.triggerChannel<0><138>=strip_imp strip_csr<13>
Project.unit<0>.triggerChannel<0><139>=strip_imp strip_csr<14>
Project.unit<0>.triggerChannel<0><13>=b_data<0>
Project.unit<0>.triggerChannel<0><140>=strip_imp strip_csr<15>
Project.unit<0>.triggerChannel<0><141>=strip_imp strip_csr<16>
Project.unit<0>.triggerChannel<0><142>=strip_imp strip_csr<17>
Project.unit<0>.triggerChannel<0><143>=strip_imp strip_csr<18>
Project.unit<0>.triggerChannel<0><144>=strip_imp strip_csr<20>
Project.unit<0>.triggerChannel<0><145>=strip_imp strip_csr<21>
Project.unit<0>.triggerChannel<0><146>=strip_imp strip_csr<23>
Project.unit<0>.triggerChannel<0><147>=strip_imp strip_csr<24>
Project.unit<0>.triggerChannel<0><148>=strip_imp strip_csr<25>
Project.unit<0>.triggerChannel<0><149>=strip_imp strip_csr<26>
Project.unit<0>.triggerChannel<0><14>=b_data<1>
Project.unit<0>.triggerChannel<0><150>=strip_imp strip_csr<27>
Project.unit<0>.triggerChannel<0><151>=strip_imp strip_csr<28>
Project.unit<0>.triggerChannel<0><152>=strip_imp strip_csr<31>
Project.unit<0>.triggerChannel<0><153>=strip_busy
Project.unit<0>.triggerChannel<0><154>=strip_ready
Project.unit<0>.triggerChannel<0><155>=strip_imp striptbm_imp TOKEN_IN
Project.unit<0>.triggerChannel<0><156>=strip_imp striptbm_imp TOKEN_OUT
Project.unit<0>.triggerChannel<0><157>=strip_imp striptbm_imp STATE_FSM_FFd2
Project.unit<0>.triggerChannel<0><158>=strip_imp striptbm_imp STATE_FSM_FFd1
Project.unit<0>.triggerChannel<0><159>=strip_imp striptbm_imp DATA_AVAILABLE
Project.unit<0>.triggerChannel<0><15>=b_data<2>
Project.unit<0>.triggerChannel<0><160>=strip_imp striptbm_imp SENT_BCO
Project.unit<0>.triggerChannel<0><161>=strip_imp G[0].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><162>=strip_imp G[0].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.triggerChannel<0><163>=strip_imp G[1].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><164>=strip_imp G[1].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.triggerChannel<0><165>=strip_imp G[2].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><166>=strip_imp G[2].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.triggerChannel<0><167>=strip_imp G[3].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><168>=strip_imp G[3].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.triggerChannel<0><169>=strip_imp G[4].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><16>=b_data<3>
Project.unit<0>.triggerChannel<0><170>=strip_imp G[4].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.triggerChannel<0><171>=strip_imp G[5].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><172>=strip_imp G[5].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.triggerChannel<0><173>=strip_imp G[0].strip_fifo_imp READ_ENABLE
Project.unit<0>.triggerChannel<0><174>=strip_imp G[1].strip_fifo_imp READ_ENABLE
Project.unit<0>.triggerChannel<0><175>=strip_imp G[2].strip_fifo_imp READ_ENABLE
Project.unit<0>.triggerChannel<0><176>=strip_imp G[3].strip_fifo_imp READ_ENABLE
Project.unit<0>.triggerChannel<0><177>=strip_imp G[4].strip_fifo_imp READ_ENABLE
Project.unit<0>.triggerChannel<0><178>=strip_imp G[5].strip_fifo_imp READ_ENABLE
Project.unit<0>.triggerChannel<0><179>=strip_imp stripclk_imp bcoclk_release
Project.unit<0>.triggerChannel<0><17>=b_data<4>
Project.unit<0>.triggerChannel<0><180>=strip_imp stripclk_imp reset
Project.unit<0>.triggerChannel<0><181>=strip_imp stripclk_imp clk_q
Project.unit<0>.triggerChannel<0><182>=local_clock_lock_lost<0>
Project.unit<0>.triggerChannel<0><183>=strip_imp stripclk_imp clkz_dcm_locked
Project.unit<0>.triggerChannel<0><184>=local_bcodelta<0>
Project.unit<0>.triggerChannel<0><185>=local_bcodelta<1>
Project.unit<0>.triggerChannel<0><186>=local_bcodelta<2>
Project.unit<0>.triggerChannel<0><187>=local_bcodelta<3>
Project.unit<0>.triggerChannel<0><188>=local_bcodelta<4>
Project.unit<0>.triggerChannel<0><189>=local_bcodelta<5>
Project.unit<0>.triggerChannel<0><18>=b_data<5>
Project.unit<0>.triggerChannel<0><190>=local_bcodelta<6>
Project.unit<0>.triggerChannel<0><191>=local_bcodelta<7>
Project.unit<0>.triggerChannel<0><192>=local_bcodelta<8>
Project.unit<0>.triggerChannel<0><193>=local_bcodelta<9>
Project.unit<0>.triggerChannel<0><194>=local_bcodelta<10>
Project.unit<0>.triggerChannel<0><195>=local_bcodelta<11>
Project.unit<0>.triggerChannel<0><196>=local_bcodelta<12>
Project.unit<0>.triggerChannel<0><197>=local_bcodelta<13>
Project.unit<0>.triggerChannel<0><198>=local_bcodelta<14>
Project.unit<0>.triggerChannel<0><199>=local_bcodelta<15>
Project.unit<0>.triggerChannel<0><19>=b_data<6>
Project.unit<0>.triggerChannel<0><1>=eth_interface data_manager_blk TX_DATA_FIFO rd_en
Project.unit<0>.triggerChannel<0><20>=b_data<7>
Project.unit<0>.triggerChannel<0><21>=eth_interface ec_wrapper ethernet_controller is_arp_req_sig
Project.unit<0>.triggerChannel<0><22>=eth_interface ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.triggerChannel<0><23>=eth_interface ec_wrapper ethernet_controller udp_data_valid
Project.unit<0>.triggerChannel<0><24>=PHY_TXEN_sig
Project.unit<0>.triggerChannel<0><25>=tx_rden
Project.unit<0>.triggerChannel<0><26>=local_stripdata_repeat
Project.unit<0>.triggerChannel<0><27>=strip_imp G[0].chipserdes0_imp ALIGNED
Project.unit<0>.triggerChannel<0><28>=strip_imp G[0].chipserdes0_imp DATA_VALID
Project.unit<0>.triggerChannel<0><29>=strip_imp G[0].chipserdes1_imp ALIGNED
Project.unit<0>.triggerChannel<0><2>=eth_interface data_manager_blk TX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><30>=strip_imp G[0].chipserdes1_imp DATA_VALID
Project.unit<0>.triggerChannel<0><31>=strip_imp G[0].chipserdes2_imp ALIGNED
Project.unit<0>.triggerChannel<0><32>=strip_imp G[0].chipserdes2_imp DATA_VALID
Project.unit<0>.triggerChannel<0><33>=strip_imp G[0].chipserdes3_imp ALIGNED
Project.unit<0>.triggerChannel<0><34>=strip_imp G[0].chipserdes3_imp DATA_VALID
Project.unit<0>.triggerChannel<0><35>=strip_imp G[0].chipserdes4_imp ALIGNED
Project.unit<0>.triggerChannel<0><36>=strip_imp G[0].chipserdes4_imp DATA_VALID
Project.unit<0>.triggerChannel<0><37>=strip_imp G[1].chipserdes0_imp ALIGNED
Project.unit<0>.triggerChannel<0><38>=strip_imp G[1].chipserdes0_imp DATA_VALID
Project.unit<0>.triggerChannel<0><39>=strip_imp G[1].chipserdes1_imp ALIGNED
Project.unit<0>.triggerChannel<0><3>=eth_interface data_manager_blk TX_DATA_FIFO wr_en
Project.unit<0>.triggerChannel<0><40>=strip_imp G[1].chipserdes1_imp DATA_VALID
Project.unit<0>.triggerChannel<0><41>=strip_imp G[1].chipserdes2_imp ALIGNED
Project.unit<0>.triggerChannel<0><42>=strip_imp G[1].chipserdes2_imp DATA_VALID
Project.unit<0>.triggerChannel<0><43>=strip_imp G[1].chipserdes3_imp ALIGNED
Project.unit<0>.triggerChannel<0><44>=strip_imp G[1].chipserdes3_imp DATA_VALID
Project.unit<0>.triggerChannel<0><45>=strip_imp G[1].chipserdes4_imp ALIGNED
Project.unit<0>.triggerChannel<0><46>=strip_imp G[1].chipserdes4_imp DATA_VALID
Project.unit<0>.triggerChannel<0><47>=strip_imp G[2].chipserdes0_imp ALIGNED
Project.unit<0>.triggerChannel<0><48>=strip_imp G[2].chipserdes0_imp DATA_VALID
Project.unit<0>.triggerChannel<0><49>=strip_imp G[2].chipserdes1_imp ALIGNED
Project.unit<0>.triggerChannel<0><4>=eth_interface data_manager_blk RX_DATA_FIFO rd_en
Project.unit<0>.triggerChannel<0><50>=strip_imp G[2].chipserdes1_imp DATA_VALID
Project.unit<0>.triggerChannel<0><51>=strip_imp G[2].chipserdes2_imp ALIGNED
Project.unit<0>.triggerChannel<0><52>=strip_imp G[2].chipserdes2_imp DATA_VALID
Project.unit<0>.triggerChannel<0><53>=strip_imp G[2].chipserdes3_imp ALIGNED
Project.unit<0>.triggerChannel<0><54>=strip_imp G[2].chipserdes3_imp DATA_VALID
Project.unit<0>.triggerChannel<0><55>=strip_imp G[2].chipserdes4_imp ALIGNED
Project.unit<0>.triggerChannel<0><56>=strip_imp G[2].chipserdes4_imp DATA_VALID
Project.unit<0>.triggerChannel<0><57>=strip_imp G[3].chipserdes0_imp ALIGNED
Project.unit<0>.triggerChannel<0><58>=strip_imp G[3].chipserdes0_imp DATA_VALID
Project.unit<0>.triggerChannel<0><59>=strip_imp G[3].chipserdes1_imp ALIGNED
Project.unit<0>.triggerChannel<0><5>=eth_interface data_manager_blk RX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><60>=strip_imp G[3].chipserdes1_imp DATA_VALID
Project.unit<0>.triggerChannel<0><61>=strip_imp G[3].chipserdes2_imp ALIGNED
Project.unit<0>.triggerChannel<0><62>=strip_imp G[3].chipserdes2_imp DATA_VALID
Project.unit<0>.triggerChannel<0><63>=strip_imp G[3].chipserdes3_imp ALIGNED
Project.unit<0>.triggerChannel<0><64>=strip_imp G[3].chipserdes3_imp DATA_VALID
Project.unit<0>.triggerChannel<0><65>=strip_imp G[3].chipserdes4_imp ALIGNED
Project.unit<0>.triggerChannel<0><66>=strip_imp G[3].chipserdes4_imp DATA_VALID
Project.unit<0>.triggerChannel<0><67>=strip_imp G[4].chipserdes0_imp ALIGNED
Project.unit<0>.triggerChannel<0><68>=strip_imp G[4].chipserdes0_imp DATA_VALID
Project.unit<0>.triggerChannel<0><69>=strip_imp G[4].chipserdes1_imp ALIGNED
Project.unit<0>.triggerChannel<0><6>=eth_interface data_manager_blk RX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwss.wsts/ram_full_i
Project.unit<0>.triggerChannel<0><70>=strip_imp G[4].chipserdes1_imp DATA_VALID
Project.unit<0>.triggerChannel<0><71>=strip_imp G[4].chipserdes2_imp ALIGNED
Project.unit<0>.triggerChannel<0><72>=strip_imp G[4].chipserdes2_imp DATA_VALID
Project.unit<0>.triggerChannel<0><73>=strip_imp G[4].chipserdes3_imp ALIGNED
Project.unit<0>.triggerChannel<0><74>=strip_imp G[4].chipserdes3_imp DATA_VALID
Project.unit<0>.triggerChannel<0><75>=strip_imp G[4].chipserdes4_imp ALIGNED
Project.unit<0>.triggerChannel<0><76>=strip_imp G[4].chipserdes4_imp DATA_VALID
Project.unit<0>.triggerChannel<0><77>=strip_imp G[5].chipserdes0_imp ALIGNED
Project.unit<0>.triggerChannel<0><78>=strip_imp G[5].chipserdes0_imp DATA_VALID
Project.unit<0>.triggerChannel<0><79>=strip_imp G[5].chipserdes1_imp ALIGNED
Project.unit<0>.triggerChannel<0><7>=eth_interface data_manager_blk RX_DATA_FIFO wr_en
Project.unit<0>.triggerChannel<0><80>=strip_imp G[5].chipserdes1_imp DATA_VALID
Project.unit<0>.triggerChannel<0><81>=strip_imp G[5].chipserdes2_imp ALIGNED
Project.unit<0>.triggerChannel<0><82>=strip_imp G[5].chipserdes2_imp DATA_VALID
Project.unit<0>.triggerChannel<0><83>=strip_imp G[5].chipserdes3_imp ALIGNED
Project.unit<0>.triggerChannel<0><84>=strip_imp G[5].chipserdes3_imp DATA_VALID
Project.unit<0>.triggerChannel<0><85>=strip_imp G[5].chipserdes4_imp ALIGNED
Project.unit<0>.triggerChannel<0><86>=strip_imp G[5].chipserdes4_imp DATA_VALID
Project.unit<0>.triggerChannel<0><87>=stackGen[0].fifo_imp full
Project.unit<0>.triggerChannel<0><88>=stackGen[0].fifo_imp rd_en
Project.unit<0>.triggerChannel<0><89>=stackGen[0].fifo_imp wr_en
Project.unit<0>.triggerChannel<0><8>=eth_interface data_manager_blk TX_CTRL_FIFO rd_en
Project.unit<0>.triggerChannel<0><90>=strip_imp trigproc_imp trigger_count_enable
Project.unit<0>.triggerChannel<0><91>=strip_imp trigproc_imp fifo_imp din<4>
Project.unit<0>.triggerChannel<0><92>=strip_imp trigproc_imp fifo_imp din<5>
Project.unit<0>.triggerChannel<0><93>=strip_imp trigproc_imp fifo_imp din<6>
Project.unit<0>.triggerChannel<0><94>=strip_imp trigproc_imp fifo_imp din<7>
Project.unit<0>.triggerChannel<0><95>=strip_imp trigproc_imp fifo_imp wr_en
Project.unit<0>.triggerChannel<0><96>=strip_imp trigproc_imp fifo_imp rd_en
Project.unit<0>.triggerChannel<0><97>=strip_imp trigproc_imp fifo_imp full
Project.unit<0>.triggerChannel<0><98>=strip_imp latched_trig
Project.unit<0>.triggerChannel<0><99>=local_data_ready
Project.unit<0>.triggerChannel<0><9>=eth_interface data_manager_blk TX_CTRL_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=200
Project.unit<0>.triggerSequencerLevels=8
Project.unit<0>.triggerSequencerType=0
Project.unit<0>.type=ilapro
