#ChipScope Core Inserter Project File Version 3.0
#Tue May 08 10:38:47 CDT 2018
Project.device.designInputFile=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_slave_ots/slave/top_cs.ngc
Project.device.designOutputFile=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_slave_ots/slave/top_cs.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/stib_slave_ots/slave/_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=*watch*
Project.filter<10>=*strip_ready_cnt*
Project.filter<11>=*strip_busy*
Project.filter<12>=*strip_clocks_locked*
Project.filter<13>=*lock*
Project.filter<14>=*strip_csr*
Project.filter<15>=*dcm_re*
Project.filter<16>=*dcm_r*
Project.filter<17>=*_sr*
Project.filter<18>=*START*
Project.filter<1>=
Project.filter<2>=*clk_z*
Project.filter<3>=*fcbo_watchdog_reset*
Project.filter<4>=*tx_rden*
Project.filter<5>=*TXEN*
Project.filter<6>=**
Project.filter<7>=*DV_*
Project.filter<8>=*tx_*
Project.filter<9>=*strip_ready*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=GMII_RXCLK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=masked_rx_wren2
Project.unit<0>.dataChannel<10>=eth_interface data_manager_blk TX_CTRL_FIFO wr_en
Project.unit<0>.dataChannel<11>=eth_interface b_enable
Project.unit<0>.dataChannel<12>=strip_imp trigproc_imp trigger_count_enable
Project.unit<0>.dataChannel<13>=strip_imp trigproc_imp fifo_imp din<4>
Project.unit<0>.dataChannel<14>=strip_imp trigproc_imp fifo_imp din<5>
Project.unit<0>.dataChannel<15>=strip_imp trigproc_imp fifo_imp din<6>
Project.unit<0>.dataChannel<16>=strip_imp trigproc_imp fifo_imp din<7>
Project.unit<0>.dataChannel<17>=strip_imp trigproc_imp fifo_imp wr_en
Project.unit<0>.dataChannel<18>=strip_imp trigproc_imp fifo_imp rd_en
Project.unit<0>.dataChannel<19>=strip_imp trigproc_imp fifo_imp full
Project.unit<0>.dataChannel<1>=eth_interface data_manager_blk TX_DATA_FIFO rd_en
Project.unit<0>.dataChannel<20>=strip_imp latched_trig
Project.unit<0>.dataChannel<21>=local_data_ready
Project.unit<0>.dataChannel<22>=local_read_done
Project.unit<0>.dataChannel<23>=local_start<0>
Project.unit<0>.dataChannel<24>=local_trigger<0>
Project.unit<0>.dataChannel<25>=b_data_we
Project.unit<0>.dataChannel<26>=b_data<0>
Project.unit<0>.dataChannel<27>=b_data<1>
Project.unit<0>.dataChannel<28>=b_data<2>
Project.unit<0>.dataChannel<29>=b_data<3>
Project.unit<0>.dataChannel<2>=eth_interface data_manager_blk TX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.dataChannel<30>=b_data<4>
Project.unit<0>.dataChannel<31>=b_data<5>
Project.unit<0>.dataChannel<32>=b_data<6>
Project.unit<0>.dataChannel<33>=b_data<7>
Project.unit<0>.dataChannel<34>=eth_interface ec_wrapper ethernet_controller is_arp_req_sig
Project.unit<0>.dataChannel<35>=eth_interface ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.dataChannel<36>=eth_interface ec_wrapper ethernet_controller udp_data_valid
Project.unit<0>.dataChannel<37>=stackGen[0].fifo_imp full
Project.unit<0>.dataChannel<38>=stackGen[0].fifo_imp rd_en
Project.unit<0>.dataChannel<39>=stackGen[0].fifo_imp wr_en
Project.unit<0>.dataChannel<3>=eth_interface data_manager_blk TX_DATA_FIFO wr_en
Project.unit<0>.dataChannel<40>=local_start_count<0>
Project.unit<0>.dataChannel<41>=local_start_count<1>
Project.unit<0>.dataChannel<42>=local_start_count<2>
Project.unit<0>.dataChannel<43>=local_start_count<3>
Project.unit<0>.dataChannel<44>=strip_imp striptbm_imp TOKEN_IN
Project.unit<0>.dataChannel<45>=strip_imp striptbm_imp TOKEN_OUT
Project.unit<0>.dataChannel<46>=local_read_actually_done
Project.unit<0>.dataChannel<47>=local_bco_time<0>
Project.unit<0>.dataChannel<48>=local_bco_time<1>
Project.unit<0>.dataChannel<49>=local_bco_time<2>
Project.unit<0>.dataChannel<4>=eth_interface data_manager_blk RX_DATA_FIFO rd_en
Project.unit<0>.dataChannel<50>=local_bco_time<3>
Project.unit<0>.dataChannel<51>=strip_imp stripclk_imp bcocounter_imp sclr
Project.unit<0>.dataChannel<52>=local_bco_zero
Project.unit<0>.dataChannel<53>=local_bco_zero_cnt<0>
Project.unit<0>.dataChannel<54>=local_bco_zero_cnt<1>
Project.unit<0>.dataChannel<55>=local_bco_zero_cnt<2>
Project.unit<0>.dataChannel<56>=local_bco_zero_cnt<3>
Project.unit<0>.dataChannel<57>=ext_cmd
Project.unit<0>.dataChannel<58>=START
Project.unit<0>.dataChannel<59>=strip_imp strip_csr<3>
Project.unit<0>.dataChannel<5>=eth_interface data_manager_blk RX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.dataChannel<60>=strip_imp strip_csr<4>
Project.unit<0>.dataChannel<61>=strip_imp strip_csr<5>
Project.unit<0>.dataChannel<62>=strip_imp strip_csr<6>
Project.unit<0>.dataChannel<63>=strip_imp strip_csr<7>
Project.unit<0>.dataChannel<64>=strip_imp strip_csr<8>
Project.unit<0>.dataChannel<65>=strip_imp strip_csr<9>
Project.unit<0>.dataChannel<66>=strip_imp strip_csr<10>
Project.unit<0>.dataChannel<67>=strip_imp strip_csr<11>
Project.unit<0>.dataChannel<68>=strip_imp strip_csr<12>
Project.unit<0>.dataChannel<69>=strip_imp strip_csr<13>
Project.unit<0>.dataChannel<6>=eth_interface data_manager_blk RX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwss.wsts/ram_full_i
Project.unit<0>.dataChannel<70>=strip_imp strip_csr<14>
Project.unit<0>.dataChannel<71>=strip_imp strip_csr<15>
Project.unit<0>.dataChannel<72>=strip_imp strip_csr<16>
Project.unit<0>.dataChannel<73>=strip_imp strip_csr<17>
Project.unit<0>.dataChannel<74>=strip_imp strip_csr<18>
Project.unit<0>.dataChannel<75>=strip_imp strip_csr<20>
Project.unit<0>.dataChannel<76>=strip_imp strip_csr<21>
Project.unit<0>.dataChannel<77>=strip_imp strip_csr<23>
Project.unit<0>.dataChannel<78>=strip_imp strip_csr<24>
Project.unit<0>.dataChannel<79>=strip_imp strip_csr<25>
Project.unit<0>.dataChannel<7>=eth_interface data_manager_blk RX_DATA_FIFO wr_en
Project.unit<0>.dataChannel<80>=strip_imp strip_csr<26>
Project.unit<0>.dataChannel<81>=strip_imp strip_csr<27>
Project.unit<0>.dataChannel<82>=strip_imp strip_csr<28>
Project.unit<0>.dataChannel<83>=strip_imp strip_csr<31>
Project.unit<0>.dataChannel<84>=strip_imp stripclk_imp dcm_fbco_locked
Project.unit<0>.dataChannel<85>=strip_imp stripclk_imp locked<0>
Project.unit<0>.dataChannel<86>=strip_imp stripclk_imp locked<1>
Project.unit<0>.dataChannel<87>=strip_clocks_locked
Project.unit<0>.dataChannel<88>=strip_busy
Project.unit<0>.dataChannel<89>=strip_ready
Project.unit<0>.dataChannel<8>=eth_interface data_manager_blk TX_CTRL_FIFO rd_en
Project.unit<0>.dataChannel<90>=PHY_TXEN_sig
Project.unit<0>.dataChannel<91>=tx_rden
Project.unit<0>.dataChannel<92>=strip_imp stripclk_imp clk_z
Project.unit<0>.dataChannel<9>=eth_interface data_manager_blk TX_CTRL_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.dataDepth=512
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=95
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=false
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=masked_rx_wren2
Project.unit<0>.triggerChannel<0><10>=eth_interface data_manager_blk TX_CTRL_FIFO wr_en
Project.unit<0>.triggerChannel<0><11>=eth_interface b_enable
Project.unit<0>.triggerChannel<0><12>=strip_imp trigproc_imp trigger_count_enable
Project.unit<0>.triggerChannel<0><13>=strip_imp trigproc_imp fifo_imp din<4>
Project.unit<0>.triggerChannel<0><14>=strip_imp trigproc_imp fifo_imp din<5>
Project.unit<0>.triggerChannel<0><15>=strip_imp trigproc_imp fifo_imp din<6>
Project.unit<0>.triggerChannel<0><16>=strip_imp trigproc_imp fifo_imp din<7>
Project.unit<0>.triggerChannel<0><17>=strip_imp trigproc_imp fifo_imp wr_en
Project.unit<0>.triggerChannel<0><18>=strip_imp trigproc_imp fifo_imp rd_en
Project.unit<0>.triggerChannel<0><19>=strip_imp trigproc_imp fifo_imp full
Project.unit<0>.triggerChannel<0><1>=eth_interface data_manager_blk TX_DATA_FIFO rd_en
Project.unit<0>.triggerChannel<0><20>=strip_imp latched_trig
Project.unit<0>.triggerChannel<0><21>=local_data_ready
Project.unit<0>.triggerChannel<0><22>=local_read_done
Project.unit<0>.triggerChannel<0><23>=local_start<0>
Project.unit<0>.triggerChannel<0><24>=local_trigger<0>
Project.unit<0>.triggerChannel<0><25>=b_data_we
Project.unit<0>.triggerChannel<0><26>=b_data<0>
Project.unit<0>.triggerChannel<0><27>=b_data<1>
Project.unit<0>.triggerChannel<0><28>=b_data<2>
Project.unit<0>.triggerChannel<0><29>=b_data<3>
Project.unit<0>.triggerChannel<0><2>=eth_interface data_manager_blk TX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><30>=b_data<4>
Project.unit<0>.triggerChannel<0><31>=b_data<5>
Project.unit<0>.triggerChannel<0><32>=b_data<6>
Project.unit<0>.triggerChannel<0><33>=b_data<7>
Project.unit<0>.triggerChannel<0><34>=eth_interface ec_wrapper ethernet_controller is_arp_req_sig
Project.unit<0>.triggerChannel<0><35>=eth_interface ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.triggerChannel<0><36>=eth_interface ec_wrapper ethernet_controller udp_data_valid
Project.unit<0>.triggerChannel<0><37>=stackGen[0].fifo_imp full
Project.unit<0>.triggerChannel<0><38>=stackGen[0].fifo_imp rd_en
Project.unit<0>.triggerChannel<0><39>=stackGen[0].fifo_imp wr_en
Project.unit<0>.triggerChannel<0><3>=eth_interface data_manager_blk TX_DATA_FIFO wr_en
Project.unit<0>.triggerChannel<0><40>=local_start_count<0>
Project.unit<0>.triggerChannel<0><41>=local_start_count<1>
Project.unit<0>.triggerChannel<0><42>=local_start_count<2>
Project.unit<0>.triggerChannel<0><43>=local_start_count<3>
Project.unit<0>.triggerChannel<0><44>=strip_imp striptbm_imp TOKEN_IN
Project.unit<0>.triggerChannel<0><45>=strip_imp striptbm_imp TOKEN_OUT
Project.unit<0>.triggerChannel<0><46>=local_read_actually_done
Project.unit<0>.triggerChannel<0><47>=local_bco_time<0>
Project.unit<0>.triggerChannel<0><48>=local_bco_time<1>
Project.unit<0>.triggerChannel<0><49>=local_bco_time<2>
Project.unit<0>.triggerChannel<0><4>=eth_interface data_manager_blk RX_DATA_FIFO rd_en
Project.unit<0>.triggerChannel<0><50>=local_bco_time<3>
Project.unit<0>.triggerChannel<0><51>=strip_imp stripclk_imp bcocounter_imp sclr
Project.unit<0>.triggerChannel<0><52>=local_bco_zero
Project.unit<0>.triggerChannel<0><53>=local_bco_zero_cnt<0>
Project.unit<0>.triggerChannel<0><54>=local_bco_zero_cnt<1>
Project.unit<0>.triggerChannel<0><55>=local_bco_zero_cnt<2>
Project.unit<0>.triggerChannel<0><56>=local_bco_zero_cnt<3>
Project.unit<0>.triggerChannel<0><57>=ext_cmd
Project.unit<0>.triggerChannel<0><58>=START
Project.unit<0>.triggerChannel<0><59>=strip_imp strip_csr<3>
Project.unit<0>.triggerChannel<0><5>=eth_interface data_manager_blk RX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.triggerChannel<0><60>=strip_imp strip_csr<4>
Project.unit<0>.triggerChannel<0><61>=strip_imp strip_csr<5>
Project.unit<0>.triggerChannel<0><62>=strip_imp strip_csr<6>
Project.unit<0>.triggerChannel<0><63>=strip_imp strip_csr<7>
Project.unit<0>.triggerChannel<0><64>=strip_imp strip_csr<8>
Project.unit<0>.triggerChannel<0><65>=strip_imp strip_csr<9>
Project.unit<0>.triggerChannel<0><66>=strip_imp strip_csr<10>
Project.unit<0>.triggerChannel<0><67>=strip_imp strip_csr<11>
Project.unit<0>.triggerChannel<0><68>=strip_imp strip_csr<12>
Project.unit<0>.triggerChannel<0><69>=strip_imp strip_csr<13>
Project.unit<0>.triggerChannel<0><6>=eth_interface data_manager_blk RX_DATA_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwss.wsts/ram_full_i
Project.unit<0>.triggerChannel<0><70>=strip_imp strip_csr<14>
Project.unit<0>.triggerChannel<0><71>=strip_imp strip_csr<15>
Project.unit<0>.triggerChannel<0><72>=strip_imp strip_csr<16>
Project.unit<0>.triggerChannel<0><73>=strip_imp strip_csr<17>
Project.unit<0>.triggerChannel<0><74>=strip_imp strip_csr<18>
Project.unit<0>.triggerChannel<0><75>=strip_imp strip_csr<20>
Project.unit<0>.triggerChannel<0><76>=strip_imp strip_csr<21>
Project.unit<0>.triggerChannel<0><77>=strip_imp strip_csr<23>
Project.unit<0>.triggerChannel<0><78>=strip_imp strip_csr<24>
Project.unit<0>.triggerChannel<0><79>=strip_imp strip_csr<25>
Project.unit<0>.triggerChannel<0><7>=eth_interface data_manager_blk RX_DATA_FIFO wr_en
Project.unit<0>.triggerChannel<0><80>=strip_imp strip_csr<26>
Project.unit<0>.triggerChannel<0><81>=strip_imp strip_csr<27>
Project.unit<0>.triggerChannel<0><82>=strip_imp strip_csr<28>
Project.unit<0>.triggerChannel<0><83>=strip_imp strip_csr<31>
Project.unit<0>.triggerChannel<0><84>=strip_imp stripclk_imp dcm_fbco_locked
Project.unit<0>.triggerChannel<0><85>=strip_imp stripclk_imp locked<0>
Project.unit<0>.triggerChannel<0><86>=strip_imp stripclk_imp locked<1>
Project.unit<0>.triggerChannel<0><87>=strip_clocks_locked
Project.unit<0>.triggerChannel<0><88>=strip_busy
Project.unit<0>.triggerChannel<0><89>=strip_ready
Project.unit<0>.triggerChannel<0><8>=eth_interface data_manager_blk TX_CTRL_FIFO rd_en
Project.unit<0>.triggerChannel<0><90>=PHY_TXEN_sig
Project.unit<0>.triggerChannel<0><91>=tx_rden
Project.unit<0>.triggerChannel<0><92>=strip_imp stripclk_imp clk_z
Project.unit<0>.triggerChannel<0><93>=strip_imp stripclk_imp fcbo_watchdog_reset
Project.unit<0>.triggerChannel<0><94>=strip_imp stripclk_imp fcbo_watchdog_reset_sig
Project.unit<0>.triggerChannel<0><9>=eth_interface data_manager_blk TX_CTRL_FIFO U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/grss.rsts/ram_empty_i
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=95
Project.unit<0>.triggerSequencerLevels=8
Project.unit<0>.triggerSequencerType=0
Project.unit<0>.type=ilapro
