#ChipScope Core Inserter Project File Version 3.0
#Mon Feb 01 15:13:05 CST 2016
Project.device.designInputFile=/home/swu/mrbots/srcs/otsdaq-firmware/work/top_cs.ngc
Project.device.designOutputFile=/home/swu/mrbots/srcs/otsdaq-firmware/work/top_cs.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/swu/mrbots/srcs/otsdaq-firmware/work/_ngo
Project.device.useSRL16=true
Project.filter.dimension=16
Project.filter<0>=*B*
Project.filter<10>=*RXD*
Project.filter<11>=*RX_D*
Project.filter<12>=*RX_DV*
Project.filter<13>=*clk*
Project.filter<14>=*clk
Project.filter<15>=clk*
Project.filter<1>=*EMPTY*
Project.filter<2>=*FULL*
Project.filter<3>=
Project.filter<4>=*TX_ENABLE*
Project.filter<5>=*TX*
Project.filter<6>=*RX_VALID*
Project.filter<7>=*IS_*
Project.filter<8>=*TXD*
Project.filter<9>=*TX_EN*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=MASTER_CLK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=37
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=eth_interface ec_wrapper ethernet_controller GMII_RX_DV
Project.unit<0>.triggerChannel<0><10>=eth_interface ec_wrapper ethernet_controller GMII_TXD<7>
Project.unit<0>.triggerChannel<0><11>=eth_interface ec_wrapper ethernet_controller GMII_TXD<6>
Project.unit<0>.triggerChannel<0><12>=eth_interface ec_wrapper ethernet_controller GMII_TXD<5>
Project.unit<0>.triggerChannel<0><13>=eth_interface ec_wrapper ethernet_controller GMII_TXD<4>
Project.unit<0>.triggerChannel<0><14>=eth_interface ec_wrapper ethernet_controller GMII_TXD<3>
Project.unit<0>.triggerChannel<0><15>=eth_interface ec_wrapper ethernet_controller GMII_TXD<2>
Project.unit<0>.triggerChannel<0><16>=eth_interface ec_wrapper ethernet_controller GMII_TXD<1>
Project.unit<0>.triggerChannel<0><17>=eth_interface ec_wrapper ethernet_controller GMII_TXD<0>
Project.unit<0>.triggerChannel<0><18>=eth_interface ec_wrapper ethernet_controller is_arp_packet_sig
Project.unit<0>.triggerChannel<0><19>=eth_interface ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.triggerChannel<0><1>=eth_interface ec_wrapper ethernet_controller GMII_RXD<7>
Project.unit<0>.triggerChannel<0><20>=eth_interface ec_wrapper ethernet_controller is_ip_packet_sig
Project.unit<0>.triggerChannel<0><21>=eth_interface ec_wrapper ethernet_controller user_rx_valid_out
Project.unit<0>.triggerChannel<0><22>=eth_interface ec_wrapper user_tx_enable_out
Project.unit<0>.triggerChannel<0><23>=eth_interface data_manager_blk rx_data_fifo_full
Project.unit<0>.triggerChannel<0><24>=eth_interface data_manager_blk rx_info_fifo_full
Project.unit<0>.triggerChannel<0><25>=eth_interface data_manager_blk tx_ctrl_info_fifo_full
Project.unit<0>.triggerChannel<0><26>=eth_interface data_manager_blk tx_data_fifo_full
Project.unit<0>.triggerChannel<0><27>=eth_interface data_manager_blk tx_data_info_fifo_full
Project.unit<0>.triggerChannel<0><28>=eth_interface data_manager_blk rx_info_fifo_empty
Project.unit<0>.triggerChannel<0><29>=eth_interface data_manager_blk tx_ctrl_info_fifo_empty
Project.unit<0>.triggerChannel<0><2>=eth_interface ec_wrapper ethernet_controller GMII_RXD<6>
Project.unit<0>.triggerChannel<0><30>=eth_interface data_manager_blk tx_data_fifo_empty
Project.unit<0>.triggerChannel<0><31>=eth_interface data_manager_blk tx_data_info_fifo_empty
Project.unit<0>.triggerChannel<0><32>=eth_interface data_manager_blk b_data_we
Project.unit<0>.triggerChannel<0><33>=eth_interface data_manager_blk b_end_packet
Project.unit<0>.triggerChannel<0><34>=eth_interface data_manager_blk user_busy
Project.unit<0>.triggerChannel<0><35>=eth_interface data_manager_blk burst_start
Project.unit<0>.triggerChannel<0><36>=eth_interface data_manager_blk burst_stop
Project.unit<0>.triggerChannel<0><37>=
Project.unit<0>.triggerChannel<0><38>=
Project.unit<0>.triggerChannel<0><39>=
Project.unit<0>.triggerChannel<0><3>=eth_interface ec_wrapper ethernet_controller GMII_RXD<5>
Project.unit<0>.triggerChannel<0><40>=
Project.unit<0>.triggerChannel<0><41>=
Project.unit<0>.triggerChannel<0><42>=
Project.unit<0>.triggerChannel<0><43>=
Project.unit<0>.triggerChannel<0><44>=
Project.unit<0>.triggerChannel<0><45>=
Project.unit<0>.triggerChannel<0><46>=
Project.unit<0>.triggerChannel<0><47>=
Project.unit<0>.triggerChannel<0><48>=
Project.unit<0>.triggerChannel<0><49>=
Project.unit<0>.triggerChannel<0><4>=eth_interface ec_wrapper ethernet_controller GMII_RXD<4>
Project.unit<0>.triggerChannel<0><50>=
Project.unit<0>.triggerChannel<0><51>=
Project.unit<0>.triggerChannel<0><52>=
Project.unit<0>.triggerChannel<0><53>=
Project.unit<0>.triggerChannel<0><54>=
Project.unit<0>.triggerChannel<0><55>=
Project.unit<0>.triggerChannel<0><56>=
Project.unit<0>.triggerChannel<0><57>=
Project.unit<0>.triggerChannel<0><58>=
Project.unit<0>.triggerChannel<0><59>=
Project.unit<0>.triggerChannel<0><5>=eth_interface ec_wrapper ethernet_controller GMII_RXD<3>
Project.unit<0>.triggerChannel<0><60>=
Project.unit<0>.triggerChannel<0><61>=
Project.unit<0>.triggerChannel<0><62>=
Project.unit<0>.triggerChannel<0><63>=
Project.unit<0>.triggerChannel<0><64>=
Project.unit<0>.triggerChannel<0><65>=
Project.unit<0>.triggerChannel<0><66>=
Project.unit<0>.triggerChannel<0><67>=
Project.unit<0>.triggerChannel<0><68>=
Project.unit<0>.triggerChannel<0><69>=
Project.unit<0>.triggerChannel<0><6>=eth_interface ec_wrapper ethernet_controller GMII_RXD<2>
Project.unit<0>.triggerChannel<0><70>=
Project.unit<0>.triggerChannel<0><71>=
Project.unit<0>.triggerChannel<0><72>=
Project.unit<0>.triggerChannel<0><73>=
Project.unit<0>.triggerChannel<0><74>=
Project.unit<0>.triggerChannel<0><75>=
Project.unit<0>.triggerChannel<0><76>=
Project.unit<0>.triggerChannel<0><77>=
Project.unit<0>.triggerChannel<0><78>=
Project.unit<0>.triggerChannel<0><79>=
Project.unit<0>.triggerChannel<0><7>=eth_interface ec_wrapper ethernet_controller GMII_RXD<1>
Project.unit<0>.triggerChannel<0><80>=
Project.unit<0>.triggerChannel<0><81>=
Project.unit<0>.triggerChannel<0><82>=
Project.unit<0>.triggerChannel<0><83>=
Project.unit<0>.triggerChannel<0><84>=
Project.unit<0>.triggerChannel<0><85>=
Project.unit<0>.triggerChannel<0><86>=
Project.unit<0>.triggerChannel<0><87>=
Project.unit<0>.triggerChannel<0><88>=
Project.unit<0>.triggerChannel<0><89>=
Project.unit<0>.triggerChannel<0><8>=eth_interface ec_wrapper ethernet_controller GMII_RXD<0>
Project.unit<0>.triggerChannel<0><90>=
Project.unit<0>.triggerChannel<0><91>=
Project.unit<0>.triggerChannel<0><92>=
Project.unit<0>.triggerChannel<0><93>=
Project.unit<0>.triggerChannel<0><94>=
Project.unit<0>.triggerChannel<0><95>=
Project.unit<0>.triggerChannel<0><96>=
Project.unit<0>.triggerChannel<0><97>=
Project.unit<0>.triggerChannel<0><98>=
Project.unit<0>.triggerChannel<0><99>=
Project.unit<0>.triggerChannel<0><9>=eth_interface ec_wrapper ethernet_controller GMII_TX_EN
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=37
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
