# Autogenerated project build script
# Mon Feb  1 14:03:07 2016

project new top
project set family kintex7
project set device xc7k325t
project set package ffg900
project set speed -2
source ../cactus/boards/kc705/firmware/cfg/settings_v7.ise.tcl
xfile add ../cactus/boards/kc705/firmware/ucf/pins.ucf
exec mkdir -p ipcore_dir
exec cp ../cactus/boards/kc705/firmware/cfg/coregen.cgp ipcore_dir
exec cp ../cactus/components/ots_ethernet/firmware/cgn/INFO_FIFO_0.xco ipcore_dir
cd ipcore_dir
exec coregen -r -b INFO_FIFO_0.xco -p coregen.cgp >& coregen.out
cd ..
xfile add ipcore_dir/INFO_FIFO_0.xco
exec mkdir -p ipcore_dir
exec cp ../cactus/boards/kc705/firmware/cfg/coregen.cgp ipcore_dir
exec cp ../cactus/components/ots_ethernet/firmware/cgn/DATA_FIFO_0.xco ipcore_dir
cd ipcore_dir
exec coregen -r -b DATA_FIFO_0.xco -p coregen.cgp >& coregen.out
cd ..
xfile add ipcore_dir/DATA_FIFO_0.xco
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_gen.v
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_chk.v
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ethernet_controller.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/reset_mgr.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/xmii_handler.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/decipherer.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/filter_data_out.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/address_container.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/icmp_ping_shift_reg.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/create_packet.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/dataout_mux.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/arp_reply.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/udp_data_splicer.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/crc_splice.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/icmp_ping_checksum_calc.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/or33.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/dest_info_container.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/user_addrs_mux.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ethernet_controller_wrapper.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_controller/ip_checksum_calc.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/burst_controller_sm.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/delay_counter.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/rx_ctl.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/ram_comm_dec.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/tx_seq_ctl.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/data_manager/data_manager.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/ethernet_interface.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/params_package.vhd
xfile add ../cactus/components/ots_ethernet/firmware/hdl/burst_traffic_controller.vhd
xfile add ../cactus/projects/ethernet_null_algo/firmware/ucf/clock_constraints.ucf
xfile add ../cactus/projects/ethernet_null_algo/firmware/hdl/TOP_LEVEL.vhd
project set top rtl top
project close
