-- Copyright 1986-2015 Xilinx, Inc. All Rights Reserved.
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity top is
  Port ( 
    NIM_COM0_P : in STD_LOGIC;
    NIM_COM0_N : in STD_LOGIC;
    NIM_COM1_P : in STD_LOGIC;
    NIM_COM1_N : in STD_LOGIC;
    NIM_COM2_P : in STD_LOGIC;
    NIM_COM2_N : in STD_LOGIC;
    NIM_COM3_P : in STD_LOGIC;
    NIM_COM3_N : in STD_LOGIC;
    NIM_OUT0_P : out STD_LOGIC;
    NIM_OUT0_N : out STD_LOGIC;
    NIM_OUT1_P : out STD_LOGIC;
    NIM_OUT1_N : out STD_LOGIC;
    NIM_OUT2_P : out STD_LOGIC;
    NIM_OUT2_N : out STD_LOGIC;
    NIM_OUT3_P : out STD_LOGIC;
    NIM_OUT3_N : out STD_LOGIC;
    BKPRSA_P : in STD_LOGIC;
    BKPRSA_N : in STD_LOGIC;
    BKPRSB_P : in STD_LOGIC;
    BKPRSB_N : in STD_LOGIC;
    TRIGA_CMS_OUT_P : out STD_LOGIC;
    TRIGA_CMS_OUT_N : out STD_LOGIC;
    TRIGB_CMS_OUT_P : out STD_LOGIC;
    TRIGB_CMS_OUT_N : out STD_LOGIC;
    TRIG53_0_P : out STD_LOGIC;
    TRIG53_0_N : out STD_LOGIC;
    TRIG53_1_P : out STD_LOGIC;
    TRIG53_1_N : out STD_LOGIC;
    TRIG53_2_P : out STD_LOGIC;
    TRIG53_2_N : out STD_LOGIC;
    TRIG53_3_P : out STD_LOGIC;
    TRIG53_3_N : out STD_LOGIC;
    TRIG53_4_P : out STD_LOGIC;
    TRIG53_4_N : out STD_LOGIC;
    TRIG53_5_P : out STD_LOGIC;
    TRIG53_5_N : out STD_LOGIC;
    TRIG53_6_P : out STD_LOGIC;
    TRIG53_6_N : out STD_LOGIC;
    TRIG53_7_P : out STD_LOGIC;
    TRIG53_7_N : out STD_LOGIC;
    TRIG53_8_P : out STD_LOGIC;
    TRIG53_8_N : out STD_LOGIC;
    TRIG53_9_P : out STD_LOGIC;
    TRIG53_9_N : out STD_LOGIC;
    TRIG53_10_P : out STD_LOGIC;
    TRIG53_10_N : out STD_LOGIC;
    TRIG53_11_P : out STD_LOGIC;
    TRIG53_11_N : out STD_LOGIC;
    TRIG40_0_P : out STD_LOGIC;
    TRIG40_0_N : out STD_LOGIC;
    TRIG40_1_P : out STD_LOGIC;
    TRIG40_1_N : out STD_LOGIC;
    TRIG40_2_P : out STD_LOGIC;
    TRIG40_2_N : out STD_LOGIC;
    TRIG40_3_P : out STD_LOGIC;
    TRIG40_3_N : out STD_LOGIC;
    TRIG40_4_P : out STD_LOGIC;
    TRIG40_4_N : out STD_LOGIC;
    TRIG40_5_P : out STD_LOGIC;
    TRIG40_5_N : out STD_LOGIC;
    CLCK53_0_P : out STD_LOGIC;
    CLCK53_0_N : out STD_LOGIC;
    CLCK53_1_P : out STD_LOGIC;
    CLCK53_1_N : out STD_LOGIC;
    CLCK53_2_P : out STD_LOGIC;
    CLCK53_2_N : out STD_LOGIC;
    CLCK53_3_P : out STD_LOGIC;
    CLCK53_3_N : out STD_LOGIC;
    CLCK53_4_P : out STD_LOGIC;
    CLCK53_4_N : out STD_LOGIC;
    CLCK53_5_P : out STD_LOGIC;
    CLCK53_5_N : out STD_LOGIC;
    CLCK53_6_P : out STD_LOGIC;
    CLCK53_6_N : out STD_LOGIC;
    CLCK53_7_P : out STD_LOGIC;
    CLCK53_7_N : out STD_LOGIC;
    CLCK53_8_P : out STD_LOGIC;
    CLCK53_8_N : out STD_LOGIC;
    CLCK53_9_P : out STD_LOGIC;
    CLCK53_9_N : out STD_LOGIC;
    CLCK53_10_P : out STD_LOGIC;
    CLCK53_10_N : out STD_LOGIC;
    CLCK53_11_P : out STD_LOGIC;
    CLCK53_11_N : out STD_LOGIC;
    CLCK40_0_P : out STD_LOGIC;
    CLCK40_0_N : out STD_LOGIC;
    CLCK40_1_P : out STD_LOGIC;
    CLCK40_1_N : out STD_LOGIC;
    CLCK40_2_P : out STD_LOGIC;
    CLCK40_2_N : out STD_LOGIC;
    CLCK40_3_P : out STD_LOGIC;
    CLCK40_3_N : out STD_LOGIC;
    CLCK40_4_P : out STD_LOGIC;
    CLCK40_4_N : out STD_LOGIC;
    CLCK40_5_P : out STD_LOGIC;
    CLCK40_5_N : out STD_LOGIC;
    CLK40A_OUT_P : out STD_LOGIC;
    CLK40A_OUT_N : out STD_LOGIC;
    CLK40B_OUT_P : out STD_LOGIC;
    CLK40B_OUT_N : out STD_LOGIC;
    CLK25_6_IN_EXT_P : in STD_LOGIC;
    CLK25_6_IN_EXT_N : in STD_LOGIC;
    DAC_SER_CLK : out STD_LOGIC;
    DAC_NSYNC : out STD_LOGIC;
    DAC_DIN : out STD_LOGIC;
    PHY_RXCLK : in STD_LOGIC;
    PHY_RXCTL_RXDV : in STD_LOGIC;
    PHY_RXD0 : in STD_LOGIC;
    PHY_RXD1 : in STD_LOGIC;
    PHY_RXD2 : in STD_LOGIC;
    PHY_RXD3 : in STD_LOGIC;
    PHY_RXD4 : in STD_LOGIC;
    PHY_RXD5 : in STD_LOGIC;
    PHY_RXD6 : in STD_LOGIC;
    PHY_RXD7 : in STD_LOGIC;
    USER_CLOCK : in STD_LOGIC;
    PHY_RESET : out STD_LOGIC;
    PHY_TXCTL_TXEN : out STD_LOGIC;
    PHY_TXD0 : out STD_LOGIC;
    PHY_TXD1 : out STD_LOGIC;
    PHY_TXD2 : out STD_LOGIC;
    PHY_TXD3 : out STD_LOGIC;
    PHY_TXD4 : out STD_LOGIC;
    PHY_TXD5 : out STD_LOGIC;
    PHY_TXD6 : out STD_LOGIC;
    PHY_TXD7 : out STD_LOGIC;
    PHY_TXER : out STD_LOGIC;
    PHY_TXC_GTXCLK : out STD_LOGIC
  );

end top;

architecture stub of top is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
begin
end;
