# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/chip_fifo/chip_fifo.xci
# IP: The module: 'chip_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/chip_fifo/chip_fifo/chip_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'chip_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/chip_fifo/chip_fifo/chip_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'chip_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/chip_fifo/chip_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'chip_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/chip_fifo/chip_fifo.xci
# IP: The module: 'chip_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/chip_fifo/chip_fifo/chip_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'chip_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/chip_fifo/chip_fifo/chip_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'chip_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/rrivera/ots/srcs/otsdaq-firmware/cactus/projects/ftbf/kc705_strip_module/top/top.srcs/sources_1/ip/chip_fifo/chip_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'chip_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
