webtalk_init -webtalk_dir C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 30 15:09:14 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1266856" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174141420_1777517734_210658789_367" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1913768c41405c24a429dbdfa5aa2326" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c9c7896b-7bc8-47f9-a378-1e73b9cae3da" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0010.Hub_#0001/DLC9-Port_#0010.Hub_#0001/6000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13636093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:01:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cfgmem -value "s25fl256sxxxxxx0-spi-x1_x2_x4" -context "labtool\\usage"
webtalk_transmit -clientid 1451853425 -regid "174141420_1777517734_210658789_367" -xml C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
