# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tffg1156-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.cache/wt [current_project]
set_property parent.project_path C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files -quiet C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.runs/NIM_CLKS_synth_1/NIM_CLKS.dcp
set_property used_in_implementation false [get_files C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.runs/NIM_CLKS_synth_1/NIM_CLKS.dcp]
add_files -quiet C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.runs/clk_wiz_1_synth_1/clk_wiz_1.dcp
set_property used_in_implementation false [get_files C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.runs/clk_wiz_1_synth_1/clk_wiz_1.dcp]
read_verilog -library xil_defaultlib {
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/crc_gen.v
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/crc_chk.v
}
read_vhdl -library xil_defaultlib {
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/hdl/TOP_LEVEL.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/src/nim_plus_package_1.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/compile/reg_32.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/compile/d_ff.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/decode_addr_NIM_Plus_2.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/decode_addr_NIM_Plus_1.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/decode_addr_NIM_Plus_3.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/decode_addr_NIM_Plus_4.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/compile/sig_gen_prog.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/compile/fs_sync_module.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/compile/section_counter.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/compile/stsp_counter.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/start_sig_mux.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/decode_addr_NIM_Plus_ctrs.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/b_fifo_mux.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/compile/cnt32_v2.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/compile/pol_sel.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/test_mux.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/compile/veto_count.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/compile/ver_code.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/read_decode.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/mux_8_to_1.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/sources_1/imports/NIMPlus/src/clk_mux_2_to_1_x_2.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/reg_16.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/DAC_Control.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/src/decode_addr_NIM_Plus.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/ff_la.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/reg_8.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/load_ctl_1_phase_4ps_fs_sync.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/ps_hold_count.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/cnt32.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/burst_mux_8_to_1.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/v_sec_60_4_in_64_out.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/compile/cnt64.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/hdl/reset_mgr.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/hdl/ethernet_interface.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/hdl/params_package.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/hdl/burst_traffic_controller.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/data_manager/burst_controller_sm.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/data_manager/rx_ctl.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/data_manager/ram_comm_dec.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/data_manager/tx_seq_ctl.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/data_manager/data_manager.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/ethernet_controller.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/xmii_handler.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/decipherer.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/filter_data_out.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/address_container.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/icmp_ping_shift_reg.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/create_packet.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/dataout_mux.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/arp_reply.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/udp_data_splicer.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/crc_splice.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/icmp_ping_checksum_calc.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/or33.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/user_addrs_mux.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/ethernet_controller_wrapper.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/fifo.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/ethImports/ethernet_controller/ip_checksum_calc.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/OT_2017_05_18/load_array_64_v_ps.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/OT_2017_05_18/Load_array_section_16.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/OT_2017_05_18/reg_64.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/OT_2017_05_18_Burst_Support/cntrs_2_b_fifo.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/OT_2017_05_18_Burst_Support/cntrs_2_b_fifo_jw121.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/OT_2017_05_18_Burst_Support/scope_probe_4ch.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/JW121_2017_05_24/v_sec_32_4_in_64_out.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/JW121_2017_05_24/mux_2_1_16ch.vhd
  C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/JW121_2017_05_24/sel_block.vhd
  U:/PREP/PREP_Modernization/Firmware_Backups/Aldec_Backups/One_Phase_Designs/CAPTAN_Plus_Designs_160MHz/AGP_2017_08_29_NIMPlus_jw121_160MHz_1Phase/NIMPlus/NIMPlus/compile/nim_plus_blk_1_phase_4ps.vhd
}
read_xdc C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/constrs_1/new/top_10.xdc
set_property used_in_implementation false [get_files C:/nimPlus_CAPTAN_+_Artix_160_New_Port_Assign/top/top.srcs/constrs_1/new/top_10.xdc]

synth_design -top top -part xc7a200tffg1156-2 -flatten_hierarchy none
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
