# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tffg1156-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.cache/wt [current_project]
set_property parent.project_path /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_verilog -library xil_defaultlib {
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/crc_gen.v
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/crc_chk.v
}
read_vhdl -library xil_defaultlib {
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/ethernet_controller.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/xmii_handler.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/decipherer.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/filter_data_out.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/address_container.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/icmp_ping_shift_reg.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/create_packet.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/dataout_mux.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/arp_reply.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/udp_data_splicer.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/crc_splice.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/icmp_ping_checksum_calc.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/or33.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/user_addrs_mux.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/ethernet_controller_wrapper.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/fifo.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/ethernet_controller/ip_checksum_calc.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/data_manager/burst_controller_sm.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/data_manager/rx_ctl.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/data_manager/ram_comm_dec.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/data_manager/tx_seq_ctl.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/data_manager/data_manager.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/hdl/reset_mgr.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/hdl/ethernet_interface.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/hdl/params_package.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/hdl/burst_traffic_controller.vhd
  /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/sources_1/imports/hdl/TOP_LEVEL.vhd
}
read_xdc /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /home/rrivera/ots/srcs/otsdaq-firmware/mu2e_coinc_source/top/top.srcs/constrs_1/new/top.xdc]

synth_design -top top -part xc7a200tffg1156-2 -flatten_hierarchy none
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
