#ChipScope Core Inserter Project File Version 3.0
#Thu Jan 27 00:47:33 UTC 2022
Project.device.designInputFile=/home/ise/VirtualBoxISESharedData/FTBF_jan2022/stib_slave_ots_24jan2022_mod/stib_slave_ots/slave/top_cs.ngc
Project.device.designOutputFile=/home/ise/VirtualBoxISESharedData/FTBF_jan2022/stib_slave_ots_24jan2022_mod/stib_slave_ots/slave/top_cs.ngc
Project.device.deviceFamily=12
Project.device.enableRPMs=true
Project.device.outputDirectory=/home/ise/VirtualBoxISESharedData/FTBF_jan2022/stib_slave_ots_24jan2022_mod/stib_slave_ots/slave/_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=*bco*
Project.filter<11>=*local*
Project.filter<12>=*delta
Project.filter<13>=*READ_EN*
Project.filter<14>=*full*
Project.filter<15>=*locked*
Project.filter<16>=*lost*
Project.filter<17>=*dcm_bco_div*
Project.filter<18>=*clk_q*
Project.filter<1>=*HALT*
Project.filter<2>=*TRIGGER*
Project.filter<3>=*EXt*
Project.filter<4>=*reset*
Project.filter<5>=*cnt*
Project.filter<6>=*thresh*
Project.filter<7>=*throttle*
Project.filter<8>=*delta*
Project.filter<9>=*local_bco*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=GMII_RXCLK
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=masked_rx_wren2
Project.unit<0>.dataChannel<10>=b_data<7>
Project.unit<0>.dataChannel<11>=eth_interface ec_wrapper ethernet_controller is_arp_req_sig
Project.unit<0>.dataChannel<12>=eth_interface ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.dataChannel<13>=ext_clk
Project.unit<0>.dataChannel<14>=PHY_TXEN_sig
Project.unit<0>.dataChannel<15>=tx_rden
Project.unit<0>.dataChannel<16>=local_stripdata_repeat
Project.unit<0>.dataChannel<17>=strip_imp G[0].chipserdes0_imp ALIGNED
Project.unit<0>.dataChannel<18>=strip_imp G[0].chipserdes0_imp DATA_VALID
Project.unit<0>.dataChannel<19>=strip_imp G[0].chipserdes1_imp ALIGNED
Project.unit<0>.dataChannel<1>=eth_interface b_enable
Project.unit<0>.dataChannel<20>=strip_imp G[0].chipserdes1_imp DATA_VALID
Project.unit<0>.dataChannel<21>=strip_imp G[0].chipserdes2_imp ALIGNED
Project.unit<0>.dataChannel<22>=strip_imp G[0].chipserdes2_imp DATA_VALID
Project.unit<0>.dataChannel<23>=strip_imp G[0].chipserdes3_imp ALIGNED
Project.unit<0>.dataChannel<24>=strip_imp G[0].chipserdes3_imp DATA_VALID
Project.unit<0>.dataChannel<25>=strip_imp G[0].chipserdes4_imp ALIGNED
Project.unit<0>.dataChannel<26>=strip_imp G[0].chipserdes4_imp DATA_VALID
Project.unit<0>.dataChannel<27>=ext_cmd
Project.unit<0>.dataChannel<28>=START
Project.unit<0>.dataChannel<29>=strip_clocks_locked
Project.unit<0>.dataChannel<2>=b_data_we
Project.unit<0>.dataChannel<30>=strip_imp stripclk_imp bcocounter_imp sclr
Project.unit<0>.dataChannel<31>=strip_imp stripclk_imp dcm_fbco_locked
Project.unit<0>.dataChannel<32>=strip_imp stripclk_imp locked<0>
Project.unit<0>.dataChannel<33>=strip_imp stripclk_imp locked<1>
Project.unit<0>.dataChannel<34>=strip_imp stripclk_imp clk_z
Project.unit<0>.dataChannel<35>=strip_imp stripclk_imp fcbo_watchdog_reset
Project.unit<0>.dataChannel<36>=strip_imp stripclk_imp fcbo_watchdog_reset_sig
Project.unit<0>.dataChannel<37>=strip_imp strip_csr<31>
Project.unit<0>.dataChannel<38>=strip_busy
Project.unit<0>.dataChannel<39>=strip_ready
Project.unit<0>.dataChannel<3>=b_data<0>
Project.unit<0>.dataChannel<40>=strip_imp G[0].strip_fifo_imp fifo_imp U0/xst_fifo_generator/gconvfifo.rf/gbiv4.fgfifo16_patch/fblk/gen_wgtr.inst_wgtr/lut_f/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.dataChannel<41>=strip_imp G[0].strip_fifo_imp fifo_imp wr_en
Project.unit<0>.dataChannel<42>=strip_imp G[0].strip_fifo_imp READ_ENABLE
Project.unit<0>.dataChannel<43>=strip_imp stripclk_imp bcoclk_release
Project.unit<0>.dataChannel<44>=strip_imp stripclk_imp reset
Project.unit<0>.dataChannel<45>=strip_imp stripclk_imp clk_q
Project.unit<0>.dataChannel<46>=local_clock_lock_lost<0>
Project.unit<0>.dataChannel<47>=strip_imp stripclk_imp clkz_dcm_locked
Project.unit<0>.dataChannel<48>=fifo_reset
Project.unit<0>.dataChannel<49>=TRIGGER
Project.unit<0>.dataChannel<4>=b_data<1>
Project.unit<0>.dataChannel<50>=HALT
Project.unit<0>.dataChannel<5>=b_data<2>
Project.unit<0>.dataChannel<6>=b_data<3>
Project.unit<0>.dataChannel<7>=b_data<4>
Project.unit<0>.dataChannel<8>=b_data<5>
Project.unit<0>.dataChannel<9>=b_data<6>
Project.unit<0>.dataDepth=512
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=51
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=false
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=eth_interface ec_wrapper ethernet_controller is_arp_req_sig
Project.unit<0>.triggerChannel<0><10>=
Project.unit<0>.triggerChannel<0><11>=
Project.unit<0>.triggerChannel<0><12>=
Project.unit<0>.triggerChannel<0><13>=
Project.unit<0>.triggerChannel<0><14>=
Project.unit<0>.triggerChannel<0><15>=
Project.unit<0>.triggerChannel<0><16>=
Project.unit<0>.triggerChannel<0><17>=
Project.unit<0>.triggerChannel<0><18>=
Project.unit<0>.triggerChannel<0><19>=
Project.unit<0>.triggerChannel<0><1>=eth_interface ec_wrapper ethernet_controller is_icmp_packet_sig
Project.unit<0>.triggerChannel<0><20>=
Project.unit<0>.triggerChannel<0><21>=
Project.unit<0>.triggerChannel<0><22>=
Project.unit<0>.triggerChannel<0><23>=
Project.unit<0>.triggerChannel<0><24>=
Project.unit<0>.triggerChannel<0><25>=
Project.unit<0>.triggerChannel<0><26>=
Project.unit<0>.triggerChannel<0><27>=
Project.unit<0>.triggerChannel<0><28>=
Project.unit<0>.triggerChannel<0><29>=
Project.unit<0>.triggerChannel<0><2>=ext_clk
Project.unit<0>.triggerChannel<0><30>=
Project.unit<0>.triggerChannel<0><31>=
Project.unit<0>.triggerChannel<0><32>=
Project.unit<0>.triggerChannel<0><33>=
Project.unit<0>.triggerChannel<0><34>=
Project.unit<0>.triggerChannel<0><35>=
Project.unit<0>.triggerChannel<0><36>=
Project.unit<0>.triggerChannel<0><37>=
Project.unit<0>.triggerChannel<0><38>=
Project.unit<0>.triggerChannel<0><39>=
Project.unit<0>.triggerChannel<0><3>=ext_cmd
Project.unit<0>.triggerChannel<0><40>=
Project.unit<0>.triggerChannel<0><41>=
Project.unit<0>.triggerChannel<0><42>=
Project.unit<0>.triggerChannel<0><43>=
Project.unit<0>.triggerChannel<0><44>=
Project.unit<0>.triggerChannel<0><45>=
Project.unit<0>.triggerChannel<0><46>=
Project.unit<0>.triggerChannel<0><47>=
Project.unit<0>.triggerChannel<0><48>=
Project.unit<0>.triggerChannel<0><49>=
Project.unit<0>.triggerChannel<0><4>=START
Project.unit<0>.triggerChannel<0><50>=
Project.unit<0>.triggerChannel<0><5>=strip_clocks_locked
Project.unit<0>.triggerChannel<0><6>=TRIGGER
Project.unit<0>.triggerChannel<0><7>=
Project.unit<0>.triggerChannel<0><8>=
Project.unit<0>.triggerChannel<0><9>=
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=7
Project.unit<0>.triggerSequencerLevels=8
Project.unit<0>.triggerSequencerType=0
Project.unit<0>.type=ilapro
