
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'TOP_LEVEL.ucf'
####################################################################################
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets MASTER_CLK]



set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXCLK]
set_property PACKAGE_PIN AB18 [get_ports PHY_RXCLK]

#set_property PACKAGE_PIN U9 [get_ports USER_CLOCK]
#set_property IOSTANDARD LVCMOS25 [get_ports USER_CLOCK]

set_property PACKAGE_PIN AB19 [get_ports PHY_RXCTL_DV]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXCTL_DV]

#RGMII uses the CTL line
#set_property PACKAGE_PIN V26 [get_ports PHY_RXER]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXER]

set_property PACKAGE_PIN AB21 [get_ports PHY_RXD0]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD0]
set_property PACKAGE_PIN AB22 [get_ports PHY_RXD1]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD1]
set_property PACKAGE_PIN AA19 [get_ports PHY_RXD2]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD2]
set_property PACKAGE_PIN AA20 [get_ports PHY_RXD3]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD3]

#RGMII uses 4 data lines
#set_property PACKAGE_PIN W23 [get_ports PHY_RXD4]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD4]
#set_property PACKAGE_PIN W24 [get_ports PHY_RXD5]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD5]
#set_property PACKAGE_PIN U22 [get_ports PHY_RXD6]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD6]
#set_property PACKAGE_PIN U23 [get_ports PHY_RXD7]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD7]

set_property PACKAGE_PIN V18 [get_ports PHY_TXC_GTXCLK]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXC_GTXCLK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets GTX_CLK]

set_property PACKAGE_PIN W18 [get_ports PHY_TXCTL_EN]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXCTL_EN]

#RGMII uses the CTL line
#set_property PACKAGE_PIN R23 [get_ports PHY_TXER]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXER]

set_property PACKAGE_PIN AA14 [get_ports PHY_TXD0]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD0]
set_property PACKAGE_PIN AA15 [get_ports PHY_TXD1]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD1]
set_property PACKAGE_PIN U19 [get_ports PHY_TXD2]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD2]
set_property PACKAGE_PIN V19 [get_ports PHY_TXD3]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD3]

#RGMII uses 4 data lines
#set_property PACKAGE_PIN T23 [get_ports PHY_TXD4]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD4]
#set_property PACKAGE_PIN T22 [get_ports PHY_TXD5]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD5]
#set_property PACKAGE_PIN T21 [get_ports PHY_TXD6]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD6]
#set_property PACKAGE_PIN T20 [get_ports PHY_TXD7]
#set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD7]

#Not sure where external reset should come from for PicoZed
# trying using SW3 on carrier
set_property PACKAGE_PIN V14 [get_ports PHY_RESET]
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RESET]

#LED1
set_property PACKAGE_PIN Y18 [get_ports PZ_ULED_1]
set_property IOSTANDARD LVCMOS25 [get_ports PZ_ULED_1]

#LED2
#set_property PACKAGE_PIN Y19 [get_ports PZ_ULED_2]
#set_property IOSTANDARD LVCMOS25 [get_ports PZ_ULED_2]



#Created by Constraints Editor (xc4vlx25-ff668-10) - 2011/09/17

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# In xdc, all clocks are related by default. This differs from ucf, where clocks are unrelated unless specified otherwise. As a result, you may now see cross-clock paths that were previously unconstrained in ucf. Commented out xdc false path constraints have been generated and can be uncommented, should you wish to remove these new paths. These commands are located after the last clock definition

# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:66
create_clock -name PHY_RXCLK -period 8.000 [get_ports PHY_RXCLK]
#Created by Constraints Editor (xc6vlx240t-ff1156-1) - 2012/08/15
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:69
# A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
#create_clock -name user_clk -period 8.000 [get_pins XLXI_6101/O]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:71
# A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp -period 16.000 [get_pins XLXI_6035/q_tmp_reg/Q]
## D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:73
## A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp_1 -period 20.000 [get_pins XLXI_6040/q_tmp_reg/Q]
## D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:75
## A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp_2 -period 40.000 [get_pins XLXI_6055/q_tmp_reg/Q]
## D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:77
## A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp_3 -period 40.000 [get_pins XLXI_6058/q_tmp_reg/Q]
## D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:79
## A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp_4 -period 40.000 [get_pins XLXI_6032/q_tmp_reg/Q]

## The following cross clock domain false path constraints can be uncommented in order to mimic ucf constraints behavior (see message at the beginning of this file)
set_false_path -from [get_clocks PHY_RXCLK] -to [get_clocks [list user_clk q_tmp q_tmp_1 q_tmp_2 q_tmp_3 q_tmp_4]]
#set_false_path -from [get_clocks user_clk] -to [get_clocks [list PHY_RXCLK q_tmp q_tmp_1 q_tmp_2 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks q_tmp] -to [get_clocks [list PHY_RXCLK user_clk q_tmp_1 q_tmp_2 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks q_tmp_1] -to [get_clocks [list PHY_RXCLK user_clk q_tmp q_tmp_2 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks q_tmp_2] -to [get_clocks [list PHY_RXCLK user_clk q_tmp q_tmp_1 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks q_tmp_3] -to [get_clocks [list PHY_RXCLK user_clk q_tmp q_tmp_1 q_tmp_2 q_tmp_4]]
set_false_path -from [get_clocks q_tmp_4] -to [get_clocks [list PHY_RXCLK user_clk q_tmp q_tmp_1 q_tmp_2 q_tmp_3]]


set_output_delay -clock PHY_RXCLK 4 [get_ports PHY_TXD*]
set_output_delay -clock PHY_RXCLK 4 [get_ports PHY_TXCTL_EN]
