
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'TOP_LEVEL.ucf'
####################################################################################


set_property PACKAGE_PIN T26 [get_ports PHY_RXCLK]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:3
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXCLK' has been applied to the port object 'PHY_RXCLK'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXCLK]
#NET "PHY_RXCLK" CLOCK_DEDICATED_ROUTE = TRUE;

set_property PACKAGE_PIN U27 [get_ports USER_CLOCK]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:7
# The conversion of 'IOSTANDARD' constraint on 'net' object 'USER_CLOCK' has been applied to the port object 'USER_CLOCK'.
set_property IOSTANDARD LVCMOS25 [get_ports USER_CLOCK]
#NET "USER_CLOCK_P" LOC = U27;
#NET "USER_CLOCK_P" IOSTANDARD = LVDS;
#NET "USER_CLOCK_N" LOC = AD11;
#NET "USER_CLOCK_N" IOSTANDARD = LVDS;


set_property PACKAGE_PIN W19 [get_ports PHY_RXCTL_DV]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:15
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXCTL_DV' has been applied to the port object 'PHY_RXCTL_DV'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXCTL_DV]
set_property PACKAGE_PIN V26 [get_ports PHY_RXER]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:17
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXER' has been applied to the port object 'PHY_RXER'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXER]
set_property PACKAGE_PIN V29 [get_ports PHY_RXD0]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:19
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXD0' has been applied to the port object 'PHY_RXD0'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD0]
set_property PACKAGE_PIN V30 [get_ports PHY_RXD1]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:21
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXD1' has been applied to the port object 'PHY_RXD1'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD1]
set_property PACKAGE_PIN V25 [get_ports PHY_RXD2]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:23
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXD2' has been applied to the port object 'PHY_RXD2'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD2]
set_property PACKAGE_PIN W26 [get_ports PHY_RXD3]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:25
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXD3' has been applied to the port object 'PHY_RXD3'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD3]
set_property PACKAGE_PIN W23 [get_ports PHY_RXD4]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:27
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXD4' has been applied to the port object 'PHY_RXD4'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD4]
set_property PACKAGE_PIN W24 [get_ports PHY_RXD5]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:29
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXD5' has been applied to the port object 'PHY_RXD5'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD5]
set_property PACKAGE_PIN U22 [get_ports PHY_RXD6]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:31
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXD6' has been applied to the port object 'PHY_RXD6'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD6]
set_property PACKAGE_PIN U23 [get_ports PHY_RXD7]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:33
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RXD7' has been applied to the port object 'PHY_RXD7'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RXD7]

set_property PACKAGE_PIN T27 [get_ports PHY_TXC_GTXCLK]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:36
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXC_GTXCLK' has been applied to the port object 'PHY_TXC_GTXCLK'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXC_GTXCLK]

set_property PACKAGE_PIN R19 [get_ports PHY_TXCTL_EN]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:39
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXCTL_EN' has been applied to the port object 'PHY_TXCTL_EN'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXCTL_EN]
set_property PACKAGE_PIN R23 [get_ports PHY_TXER]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:41
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXER' has been applied to the port object 'PHY_TXER'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXER]
set_property PACKAGE_PIN P28 [get_ports PHY_TXD0]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:43
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXD0' has been applied to the port object 'PHY_TXD0'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD0]
set_property PACKAGE_PIN P27 [get_ports PHY_TXD1]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:45
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXD1' has been applied to the port object 'PHY_TXD1'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD1]
set_property PACKAGE_PIN R29 [get_ports PHY_TXD2]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:47
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXD2' has been applied to the port object 'PHY_TXD2'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD2]
set_property PACKAGE_PIN P29 [get_ports PHY_TXD3]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:49
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXD3' has been applied to the port object 'PHY_TXD3'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD3]
set_property PACKAGE_PIN T23 [get_ports PHY_TXD4]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:51
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXD4' has been applied to the port object 'PHY_TXD4'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD4]
set_property PACKAGE_PIN T22 [get_ports PHY_TXD5]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:53
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXD5' has been applied to the port object 'PHY_TXD5'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD5]
set_property PACKAGE_PIN T21 [get_ports PHY_TXD6]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:55
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXD6' has been applied to the port object 'PHY_TXD6'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD6]
set_property PACKAGE_PIN T20 [get_ports PHY_TXD7]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:57
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_TXD7' has been applied to the port object 'PHY_TXD7'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_TXD7]

set_property PACKAGE_PIN U20 [get_ports PHY_RESET]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:60
# The conversion of 'IOSTANDARD' constraint on 'net' object 'PHY_RESET' has been applied to the port object 'PHY_RESET'.
set_property IOSTANDARD LVCMOS25 [get_ports PHY_RESET]


#Created by Constraints Editor (xc4vlx25-ff668-10) - 2011/09/17

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# In xdc, all clocks are related by default. This differs from ucf, where clocks are unrelated unless specified otherwise. As a result, you may now see cross-clock paths that were previously unconstrained in ucf. Commented out xdc false path constraints have been generated and can be uncommented, should you wish to remove these new paths. These commands are located after the last clock definition

# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:66
create_clock -name PHY_RXCLK -period 8.000 [get_ports PHY_RXCLK]
#Created by Constraints Editor (xc6vlx240t-ff1156-1) - 2012/08/15
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:69
# A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name user_clk -period 5.000 [get_pins XLXI_6101/O]
# D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:71
# A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp -period 10.000 [get_pins XLXI_6035/q_tmp_reg/Q]
## D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:73
## A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp_1 -period 20.000 [get_pins XLXI_6040/q_tmp_reg/Q]
## D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:75
## A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp_2 -period 40.000 [get_pins XLXI_6055/q_tmp_reg/Q]
## D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:77
## A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp_3 -period 40.000 [get_pins XLXI_6058/q_tmp_reg/Q]
## D:/Projects/CAPTANplusX/fw_00/GEL_CAPTAN/TOP_LEVEL.ucf:79
## A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name q_tmp_4 -period 40.000 [get_pins XLXI_6032/q_tmp_reg/Q]

## The following cross clock domain false path constraints can be uncommented in order to mimic ucf constraints behavior (see message at the beginning of this file)
set_false_path -from [get_clocks PHY_RXCLK] -to [get_clocks [list user_clk q_tmp q_tmp_1 q_tmp_2 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks user_clk] -to [get_clocks [list PHY_RXCLK q_tmp q_tmp_1 q_tmp_2 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks q_tmp] -to [get_clocks [list PHY_RXCLK user_clk q_tmp_1 q_tmp_2 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks q_tmp_1] -to [get_clocks [list PHY_RXCLK user_clk q_tmp q_tmp_2 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks q_tmp_2] -to [get_clocks [list PHY_RXCLK user_clk q_tmp q_tmp_1 q_tmp_3 q_tmp_4]]
set_false_path -from [get_clocks q_tmp_3] -to [get_clocks [list PHY_RXCLK user_clk q_tmp q_tmp_1 q_tmp_2 q_tmp_4]]
set_false_path -from [get_clocks q_tmp_4] -to [get_clocks [list PHY_RXCLK user_clk q_tmp q_tmp_1 q_tmp_2 q_tmp_3]]

